### PR TITLE
fix handling of multimodal Content parameters in AiServices

### LINKED ISSUE #4352: [BUG] AI Service: wrong treatment of multimodal content
**Describe the bug**
```java
    interface Assistant {
        TokenStream chat(AudioContent audio);
    }
```

In this case `AudioContent` is not treated as a content, it is converted into `String` and sent to the model as `TextContent`.

**Log and Stack trace**
```
- method: POST
- url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:streamGenerateContent?alt=sse
- headers: [x-goog-api-key: AIzaS...r0], [User-Agent: LangChain4j], [Content-Type: application/json]
- body: {
  "contents" : [ {
    "parts" : [ {
      "text" : "AudioContent { audio = Audio { url = null, base64Data = \"AAAAGGZ0eXBtcDQyAAAAAG1wNDFpc29tAAAAKHV1aWRcpwj7Mo5CBahhZQ7KCpWWAAAADDEwLjAuMjYy....
```

**Expected behavior**

If argument of AI Service method is a subtype of `dev.langchain4j.data.message.Content`, it should not be converted to `String`/`TextContent`, but sent to the LLM as-is.

**Please complete the following information:**
- LangChain4j version: 1.10.0
- LLM(s) used: Google AI Gemini
- Java version: 21

### PR DESCRIPTION
**Pull request by jujn**
## Issue
Closes #4352

## General checklist
- [X] There are no breaking changes (API, behaviour)
- [X] I have added unit and/or integration tests for my change
- [ ] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

File: langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java [hunk 1]
```diff
@@ -508,6 +508,14 @@ private Optional<String> findSystemMessageTemplate(Object memoryId, Method metho
 
     private static UserMessage prepareUserMessage(
             Method method, Object[] args, String userMessageTemplate, Map<String, Object> variables) {
+        if (userMessageTemplate == null || userMessageTemplate.trim().isEmpty()) {
+            Optional<String> maybeUserName = findUserName(method.getParameters(), args);
+
+            return maybeUserName
+                    .map(userName -> UserMessage.from(userName, "M"))
```
Comment (dliubarskyi) [inline langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java]: What is "M"?

File: langchain4j/src/test/java/dev/langchain4j/service/AiServicesMultimodalTest.java [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+import dev.langchain4j.model.chat.response.ChatResponse;
+import java.util.List;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.ExtendWith;
+import org.mockito.ArgumentCaptor;
+import org.mockito.Mock;
+import org.mockito.junit.jupiter.MockitoExtension;
+
+@ExtendWith(MockitoExtension.class)
+class AiServicesMultimodalTest {
```
Comment (dliubarskyi) [inline langchain4j/src/test/java/dev/langchain4j/service/AiServicesMultimodalTest.java]: Please add new tests to `AiServicesUserMessageConfigTest` instead of creating a new one

File: langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java (hunk 1 above)
Comment (jujn) [reply langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java]: > What is "M"?

Sorry about the 'M', that was a placeholder. I realized that TextContent validation fails on empty strings. I've updated the logic to construct the initial UserMessage using the actual Content (Audio/Image) from the arguments.

File: langchain4j/src/test/java/dev/langchain4j/service/AiServicesMultimodalTest.java (hunk 2 above)
Comment (jujn) [reply langchain4j/src/test/java/dev/langchain4j/service/AiServicesMultimodalTest.java]: > Please add new tests to `AiServicesUserMessageConfigTest` instead of creating a new one

done

File: langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java [hunk 3]
```diff
@@ -508,6 +508,26 @@ private Optional<String> findSystemMessageTemplate(Object memoryId, Method metho
 
     private static UserMessage prepareUserMessage(
             Method method, Object[] args, String userMessageTemplate, Map<String, Object> variables) {
+        if (userMessageTemplate.isEmpty()) {
+            Optional<String> maybeUserName = findUserName(method.getParameters(), args);
+
+            for (Object arg : args) {
+                if (arg instanceof Content) {
```
Comment (dliubarskyi) [inline langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java]:
```suggestion
                if (arg instanceof Content content) {
```
nit

File: langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java [hunk 4]
```diff
@@ -508,6 +508,26 @@ private Optional<String> findSystemMessageTemplate(Object memoryId, Method metho
...
+                            .orElseGet(() -> UserMessage.from(content));
+                } else if (isListOfContents(arg)) {
+                    List<Content> contents = (List<Content>) arg;
+                    return maybeUserName
+                            .map(userName -> UserMessage.from(userName, contents))
+                            .orElseGet(() -> UserMessage.from(contents));
+                }
+            }
+
+            return UserMessage.from(" ");
```
Comment (dliubarskyi) [inline langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java]: Can we please avoid doing this?

File: langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java [hunk 5]
```diff
@@ -508,6 +508,26 @@ private Optional<String> findSystemMessageTemplate(Object memoryId, Method metho
 
     private static UserMessage prepareUserMessage(
             Method method, Object[] args, String userMessageTemplate, Map<String, Object> variables) {
+        if (userMessageTemplate.isEmpty()) {
+            Optional<String> maybeUserName = findUserName(method.getParameters(), args);
+
+            for (Object arg : args) {
+                if (arg instanceof Content) {
+                    Content content = (Content) arg;
+                    return maybeUserName
```
Comment (dliubarskyi) [inline langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java]: what if we have more than 1 argument of type `Content`? This returns too early

Comment (dliubarskyi) [reply langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java]: please add a test for this case

File: langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java (hunk 4 above)
Comment (jujn) [reply langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java]: > Can we please avoid doing this?

Sorry about that. I accidentally pushed a local testing version, and I forget to check it. I have updated it with the correct implementation.

**Review by dliubarskyi — APPROVED** [review]
@jujn thank you!
