### PR TITLE
Always make sure query transformer has access to system message in memory

### LINKED ISSUE #4113: [BUG] SystemMessage is not accessible in the query transformer for the 1st user message
**Describe the bug**

It's noticed that the `query.metadata().chatMemory()` is empty without system message when the 1st user message is processed in `QueryTransformer`. However for all following user messages starting from the _2nd_ one, the `query.metadata().chatMemory()` has system message as the _1st_ message.

It seems that system message is added into the memory only after query transformer is called via the augmenter. Wonder is this expected? Can we move [this logic](https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java#L319) to before calling query transformer so that the system message is accessible from the query transformer, same as the behavior where system message is accessible to all following user messages (starting from the _2nd_ one)?

**Log and Stack trace**

**To Reproduce**

Send the very 1st user message to the LLM and observe the `query.metadata().chatMemory()`.

**Expected behavior**

`query.metadata().chatMemory()` contains system message when processing the 1st user message.

**Please complete the following information:**
- LangChain4j version: v1.8.0
- LLM(s) used: gpt-4.1-mini
- Java version: 17
- Spring Boot version (if applicable): 

**Additional context**

### PR DESCRIPTION
**Pull request by YSZhuoyang**
## Issue

Closes https://github.com/langchain4j/langchain4j/issues/4113

## Change

This PR makes sure system message is added to memory before query transformer is called, such that the query transformer has access to system message in memory when the very first user message is processed.

## General checklist

- [X] There are no breaking changes (API, behaviour)
- [X] I have added unit and/or integration tests for my change
- [ ] The tests cover both positive and negative cases <--- _I'm not changing negative cases_
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by YSZhuoyang** [comment]
core module test results:

```
[WARNING] Tests run: 761, Failures: 0, Errors: 0, Skipped: 5
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.624 s
[INFO] Finished at: 2025-11-25T22:16:17+11:00
[INFO] ------------------------------------------------------------------------
```

main module test results:

```
[INFO] Results:
[INFO] 
[WARNING] Tests run: 1091, Failures: 0, Errors: 0, Skipped: 3
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.887 s
[INFO] Finished at: 2025-11-25T22:17:31+11:00
[INFO] ------------------------------------------------------------------------
```

File: langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java [hunk 1]
```diff
@@ -56,7 +56,6 @@
 import java.util.ArrayList;
 import java.util.Arrays;
 import java.util.Collection;
-import java.util.HashMap;
```
Comment (YSZhuoyang) [inline langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java]: not used anywhere

File: langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithRagIT.java [hunk 2]
```diff
@@ -19,16 +19,6 @@
 import static org.mockito.Mockito.verifyNoMoreInteractions;
 import static org.mockito.Mockito.when;
 
-import java.net.URISyntaxException;
```
Comment (YSZhuoyang) [inline langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithRagIT.java:22]: spotless apply requested by ci

**Review by dliubarskyi — APPROVED** [review]
@YSZhuoyang thank you!

**Comment by lglauer** [comment]
@dliubarskyi I think this change introduces an unintended side effect in `CompressingQueryTransformer`. CompressingQueryTransformer should do nothing for the first user message. Since the system message is now always present in the chat memory, the condition in CompressingQueryTransformer `chatMemory.isEmpty()` evaluates to false and compression is already applied to the very first user message. This is a bug, right?
