### PR TITLE
fix typo method on AiServiceTokenStreamParameters

### LINKED ISSUE #4320: [BUG]  Typo method naming on AiServiceTokenStreamParameters
**Describe the bug**

Typo: https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStreamParameters.java#L93

**Log and Stack trace**

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version:
- LLM(s) used: 
- Java version: 
- Spring Boot version (if applicable): 

**Additional context**

### PR DESCRIPTION
**Pull request by omarmahamid**
## Issue
Closes https://github.com/langchain4j/langchain4j/issues/4320

## General checklist
- [ ] There are no breaking changes (API, behaviour)
- [ ] I have added unit and/or integration tests for my change
- [ ] The tests cover both positive and negative cases
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

File: langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStream.java [hunk 1]
```diff
@@ -85,7 +85,7 @@ public AiServiceTokenStream(AiServiceTokenStreamParameters parameters) {
         this.toolArgumentsErrorHandler = parameters.toolArgumentsErrorHandler();
         this.toolExecutionErrorHandler = parameters.toolExecutionErrorHandler();
         this.toolExecutor = parameters.toolExecutor();
-        this.retrievedContents = copy(parameters.gretrievedContents());
+        this.retrievedContents = copy(parameters.getRetrievedContents());
```
Comment (dliubarskyi) [inline langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStream.java]:
```suggestion
        this.retrievedContents = copy(parameters.retrievedContents());
```

File: langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStreamParameters.java [hunk 2]
```diff
@@ -90,7 +90,7 @@ public Executor toolExecutor() {
     /**
      * @return the retrieved contents
      */
-    public List<Content> gretrievedContents() {
+    public List<Content> getRetrievedContents() {
```
Comment (dliubarskyi) [inline langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStreamParameters.java]:
```suggestion
    public List<Content> retrievedContents() {
```

**Review by dliubarskyi — APPROVED** [review]
@omarmahamid thank you!
