### PR TITLE
fix: #3091 change single parameter detection logic and add tests

### LINKED ISSUE #3091: [BUG] Use non-langchain4j annotations breaks AiService `@UserMessage` single argument method defaulting
**Describe the bug**

Adding a non-langchain4j annotation to an AI Service breaks `@UserMessage` defaulting for single argument methods.

For example, using just OTEL annotations does not work:
```
  public interface TaskService {
    @WithSpan String task(@SpanAttribute String userMessage);
  }
```

However, using no annotation or explicit `@UserMessage` does work:
```
  public interface TaskService {
    @WithSpan String task(String userMessage);
  }
  public interface TaskService {
    @WithSpan String task(@SpanAttribute @UserMessage String userMessage);
  }
```

The reasons is that DefaultAiServices is not filtering to look for only langchain4j annotations:  https://github.com/langchain4j/langchain4j/blob/35d8bee5db5e30fbd969a867a5fd29131ad6bf7e/langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java#L379C75-L379C89

**Log and Stack trace**
```
Caused by: dev.langchain4j.service.IllegalConfigurationException: Error: The method 'task' does not have a user message defined.
	at dev.langchain4j.service.IllegalConfigurationException.illegalConfiguration(IllegalConfigurationException.java:18)
	at dev.langchain4j.service.DefaultAiServices.getUserMessageTemplate(DefaultAiServices.java:360)
	at dev.langchain4j.service.DefaultAiServices.prepareUserMessage(DefaultAiServices.java:323)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:151)
```
**To Reproduce**

**Expected behavior**

Adding a non-langchain4j annotation should not break existing working langchain4j behaviors.

**Please complete the following information:**
- LangChain4j version: 1.0.1
- Java version:  21

### PR DESCRIPTION
**Pull request by raphidlee**
## Issue

Closes #3091 

## Change

Fixes a bug where any non-langchain4j annotation on a single-parameter method prevents the default @UserMessage detection from working correctly.

Changes:

If a method has exactly one parameter, and that parameter does not annotated @UserMessage annotation, it is now correctly treated as a default @UserMessage.
Added tests.

This is a cleaned-up successor to PR #4154 .
Same feature, but rebased and refactored to remove conflicts and simplify review.

## General checklist

- [X] There are no breaking changes (API, behaviour)
- [X] I have added unit and/or integration tests for my change
- [X] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [X] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by raphidlee** [comment]
Hi @dliubarskyi  — when you have time, could you take a look at this PR?
Happy to adjust direction based on your feedback.

File: langchain4j/src/test/java/dev/langchain4j/service/AiServicesTest.java [hunk 1]
```diff
@@ -121,4 +142,92 @@ void should_preserve_interface_type() {
...
+        }
+
+        stubChatModelToReturnHi();
+        TaskService taskService = buildService(TaskService.class);
+
+        assertThat(taskService.task("Hello")).isEqualTo("Hi");
+    }
+
+    @Test
+    void should_use_annotated_user_message_with_multiple_parameters() {
```
Comment (dliubarskyi) [inline langchain4j/src/test/java/dev/langchain4j/service/AiServicesTest.java]: I think many of the new tests here already exist in `AiServicesUserMessageConfigTest`, could you please remove those which are duplicated?

File: langchain4j/src/test/java/dev/langchain4j/service/AiServicesTest.java [hunk 2]
```diff
@@ -121,4 +142,92 @@ void should_preserve_interface_type() {
...
         assertThat(Assistant.class.isAssignableFrom(assistant.getClass())).isTrue();
     }
+
+    /**
+     * Regression test for https://github.com/langchain4j/langchain4j/issues/3091
+     * Verifies that single-argument defaulting still works when a non-langchain4j
+     * annotation is present on the parameter.
+     */
+    @Test
+    void should_detect_single_parameter_as_user_message_even_with_other_annotations() {
```
Comment (dliubarskyi) [inline langchain4j/src/test/java/dev/langchain4j/service/AiServicesTest.java]: Could you please move this test to `AiServicesUserMessageConfigTest`?

**Review by dliubarskyi — COMMENTED** [review]
@raphidlee thank you!

**Comment by raphidlee** [comment]
@dliubarskyi 
Thanks for the review! I’ve updated the test case location as suggested and pushed the changes.

**Review by dliubarskyi — APPROVED** [review]
@raphidlee thank you!
