### PR TITLE
Ollama chat model listener

### LINKED ISSUE #1750: [BUG] OllamaStreamingLanguageModel throws EOFException
**Describe the bug**

Using StreamingLanguageModel to generate response from model and when response from model is short then is working fine. But when model response a lot of it throws: `com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 1025 path $.context[0]`
I using local model: llama2, exception throws around 1 minute after generating response.

**Log and Stack trace**

```
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 1025 path $.context[0]
        at com.google.gson.Gson.fromJson(Gson.java:1370)
        at com.google.gson.Gson.fromJson(Gson.java:1262)                                                                                                                                                                                
        at com.google.gson.Gson.fromJson(Gson.java:1171)                                                                                                                                                                                
        at com.google.gson.Gson.fromJson(Gson.java:1107)                                                                                                                                                                                
        at dev.langchain4j.model.ollama.OllamaClient$1.onResponse(OllamaClient.java:120)                                                                                                                                                
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)                                                                                                                                                                       
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)                                                                                                                                                          
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                                                                                                                    
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                                                                                                                    
        at java.base/java.lang.Thread.run(Thread.java:840)                                                                                                                                                                              
Caused by: java.io.EOFException: End of input at line 1 column 1025 path $.context[0]                                                                                                                                                   
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1542)                                                                                                                                                    
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:550)                                                                                                                                                                
        at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1339)                                                                                                                                                            
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:514)                                                                                                               
        at com.google.gson.Gson.fromJson(Gson.java:1361)                                                                                                                                                                                
        ... 9 more     
```
**To Reproduce**
```
<!-- Please provide a relevant code snippets to reproduce this bug. -->
 StreamingLanguageModel ollama = OllamaStreamingLanguageModel.builder()
            .baseUrl("http://localhost:11434/")
            .modelName("llama2")
            .build();

CompletableFuture<String> future = new CompletableFuture<>();
ollama.generate("why the sky is blue?", new StreamingResponseHandler<String>() {

            @Override
            public void onNext(String token) {
                System.out.println(token);
            }

            @Override
            public void onComplete(dev.langchain4j.model.output.Response<String> response) {
                future.complete(response.toString());
            }

            @Override
            public void onError(Throwable error) {
                error.printStackTrace();
            }
        });
        future.join();
```
**Expected behavior**

No exception is thrown when processing streaming response.

**Please complete the following information:**
- LangChain4j version: 0.32.0
- LLM(s) used: Ollama llama2
- Java version: 17

### LINKED ISSUE #1756: Ollama: add ChatModelListener support
Add `ChatModelListener` support to `OllamaChatModel` and `OllamaStreamingChatModel`.
See `OpenAiChatModel` and `OpenAiStreamingChatModel` as an example.

### PR DESCRIPTION
**Pull request by Martin7-1**
## Issue
Closes #1756
Closes #1750

## Change
1. `OllamaChatModel` and `OllamaStreamingChatModel` support `ChatListener`
2. Fix `OllamaStreamingLanguageModel` throws `EOFException` when the response content is too long.

All tests are green on my local environment :)

## General checklist

- [x] There are no breaking changes
- [x] I have added unit and integration tests for my change
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java [hunk 1]
```diff
@@ -82,26 +96,18 @@ public static OllamaChatModelBuilder builder() {
...
-                AiMessage.from(response.getMessage().getContent()),
-                new TokenUsage(response.getPromptEvalCount(), response.getEvalCount())
-        );
+        return doGenerate(messages, null);
     }
 
     @Override
     public Response<AiMessage> generate(List<ChatMessage> messages, List<ToolSpecification> toolSpecifications) {
         ensureNotEmpty(messages, "messages");
+        ensureNotEmpty(toolSpecifications, "toolSpecifications");
```
Comment (langchain4j) [inline langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java]: not sure about this change, it might break for someone

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java [hunk 2]
```diff
@@ -111,14 +117,39 @@ public Response<AiMessage> generate(List<ChatMessage> messages, List<ToolSpecifi
...
+            return response;
+        } catch (Exception e) {
+            ChatModelErrorContext errorContext = new ChatModelErrorContext(
+                    e,
+                    modelListenerRequest,
+                    null,
+                    attributes
+            );
+
+            listeners.forEach(listener -> {
```
Comment (langchain4j) [inline langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java]: Shouldn't it call `OllamaChatModelListenerUtils.onListenError()` here instead?

File: langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaOpenAiStreamingChatModelIT.java [hunk 3]
```diff
@@ -47,5 +52,73 @@ void should_generate_response() {
         assertThat(response.finishReason()).isEqualTo(STOP);
     }
 
+    @Test
+    void should_listen_request_and_response() {
```
Comment (langchain4j) [inline langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaOpenAiStreamingChatModelIT.java]: I am not sure this test is required, it is already tested in `OpenAiStreamingChatModelIT`

File: langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaOpenAiChatModelIT.java [hunk 4]
```diff
@@ -50,5 +56,123 @@ void should_generate_response() {
         assertThat(response.finishReason()).isEqualTo(STOP);
     }
 
+    @Test
+    void should_listen_request_and_response() {
```
Comment (langchain4j) [inline langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaOpenAiChatModelIT.java]: I am not sure these tests are required, it is already tested in `OpenAiChatModelIT`

**Review by ghost — COMMENTED** [review]
@Martin7-1 thanks a lot!

A few tests are failing on my env:

`OllamaStreamingChatModelIT.should_listen_error()`:
```
2024-09-12 10:48:53 [OkHttp https://banana/...] dev.langchain4j.model.ollama.OllamaRequestLoggingInterceptor.log()
DEBUG: Request:
- method: POST
- url: https://banana/api/chat
- headers: 
- body: {
  "model" : "tinydolphin",
  "messages" : [ {
    "role" : "user",
    "content" : "this message will fail"
  } ],
  "options" : { },
  "stream" : true
}
org.opentest4j.AssertionFailedError: 
expected: null
 but was: dev.langchain4j.model.chat.listener.ChatModelResponse@1228ac21
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at dev.langchain4j.model.ollama.OllamaStreamingChatModelIT$3.onError(OllamaStreamingChatModelIT.java:288)
	at dev.langchain4j.model.ollama.OllamaChatModelListenerUtils.lambda$onListenError$2(OllamaChatModelListenerUtils.java:83)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at dev.langchain4j.model.ollama.OllamaChatModelListenerUtils.onListenError(OllamaChatModelListenerUtils.java:81)
	at dev.langchain4j.model.ollama.OllamaClient$2.onFailure(OllamaClient.java:199)
	at retrofit2.OkHttpCall$1.callFailure(OkHttpCall.java:175)
	at retrofit2.OkHttpCall$1.onFailure(OkHttpCall.java:170)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

java.lang.AssertionError: 
Expecting throwable message:
  "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"
to contain:
  "Name or service not known"
but did not.

Throwable that failed the check:

javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1195)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1138)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:447)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at dev.langchain4j.model.ollama.OllamaRequestLoggingInterceptor.intercept(OllamaRequestLoggingInterceptor.java:70)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:271)
	at java.base/sun.security.validator.Validator.validate(Validator.java:256)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1302)
	... 33 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383)
	... 38 more


	at dev.langchain4j.model.ollama.OllamaStreamingChatModelIT.should_listen_error(OllamaStreamingChatModelIT.java:327)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

`OllamaChatModelIT.should_listen_error()`:
```
2024-09-12 10:48:53 [main] dev.langchain4j.model.ollama.OllamaRequestLoggingInterceptor.log()
DEBUG: Request:
- method: POST
- url: http://banana/api/chat
- headers: 
- body: {
  "model" : "tinydolphin",
  "messages" : [ {
    "role" : "user",
    "content" : "this message will fail"
  } ],
  "options" : { },
  "stream" : false
}
2024-09-12 10:48:53 [main] dev.langchain4j.model.ollama.OllamaResponseLoggingInterceptor.log()
DEBUG: Response:
- status code: 404
- headers: Date: Thu, 12 Sep 2024 08:48:53 GMT
Content-Type: text/html
Content-Length: 146
Connection: keep-alive

- body: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>


java.lang.AssertionError: 
Expecting throwable message:
  "java.lang.RuntimeException: status code: 404; body: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
"
to contain:
  "Name or service not known"
but did not.

Throwable that failed the check:

java.lang.RuntimeException: java.lang.RuntimeException: status code: 404; body: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.ollama.OllamaChatModel.doGenerate(OllamaChatModel.java:125)
	at dev.langchain4j.model.ollama.OllamaChatModel.generate(OllamaChatModel.java:99)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:44)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:32)
	at dev.langchain4j.model.ollama.OllamaChatModelIT.lambda$should_listen_error$0(OllamaChatModelIT.java:240)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3111)
	at dev.langchain4j.model.ollama.OllamaChatModelIT.should_listen_error(OllamaChatModelIT.java:240)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:218)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:214)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:139)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:63)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.lang.RuntimeException: status code: 404; body: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at dev.langchain4j.model.ollama.OllamaClient.toException(OllamaClient.java:275)
	at dev.langchain4j.model.ollama.OllamaClient.chat(OllamaClient.java:102)
	at dev.langchain4j.model.ollama.OllamaChatModel.lambda$doGenerate$0(OllamaChatModel.java:125)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	... 78 more


	at dev.langchain4j.model.ollama.OllamaChatModelIT.should_listen_error(OllamaChatModelIT.java:244)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java (hunk 1 above)
Comment (Martin7-1) [reply langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java]: OK. I revert this check now.

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java (hunk 2 above)
Comment (Martin7-1) [reply langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java]: Done.

File: langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaOpenAiStreamingChatModelIT.java (hunk 3 above)
Comment (Martin7-1) [reply langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaOpenAiStreamingChatModelIT.java]: hmmm. Maybe it's no need to test it.

File: langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaOpenAiChatModelIT.java (hunk 4 above)
Comment (Martin7-1) [reply langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaOpenAiChatModelIT.java]: Maybe it's no need to test it.

**Comment by Martin7-1** [comment]
The `should_listen_error` tests are hard to determine which Exception and what message has throw... In my local environment the test throw `java.net.UnknownHostException: banana: Name or service not known`.

Maybe the check of Exception message and type should be removed. Is there any better way to test it?

**Review by ghost — COMMENTED** [review]
`should_listen_error` is failing now with:

```
org.opentest4j.AssertionFailedError: 
expected: "12345"
 but was: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at dev.langchain4j.model.ollama.OllamaStreamingChatModelIT$3.onError(OllamaStreamingChatModelIT.java:289)
	at dev.langchain4j.model.ollama.OllamaChatModelListenerUtils.lambda$onListenError$2(OllamaChatModelListenerUtils.java:83)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at dev.langchain4j.model.ollama.OllamaChatModelListenerUtils.onListenError(OllamaChatModelListenerUtils.java:81)
	at dev.langchain4j.model.ollama.OllamaClient$2.onResponse(OllamaClient.java:189)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

It seems that attributes are not passsed from one listener method to another

**Comment by Martin7-1** [comment]
image

@langchain4j I made a mistake that I don't reuse the same attributes. Now the tests can passed :)

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaHttpException.java [hunk 5]
```diff
@@ -0,0 +1,12 @@
+package dev.langchain4j.model.ollama;
+
+public class OllamaHttpException extends RuntimeException {
```
Comment (langchain4j) [inline langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaHttpException.java]: I am not sure about this new exception type, it does not seem to bring much (just wraps original exception), but might break something for existing users...

Comment (Martin7-1) [reply langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaHttpException.java]: Hmmm...You are right. The purpose for this class is that `StreamingChat` and `StreamingCompletion` in `OllamaClient` throw original Exception which is hard to assert. Maybe wrap them with `RuntimeException` will not break cur implementation.

Comment (Martin7-1) [reply langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaHttpException.java]: I remove it now.

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java [hunk 6]
```diff
@@ -164,30 +174,33 @@ public void onResponse(Call<ResponseBody> call, retrofit2.Response<ResponseBody>
...
+                                onListenResponse(listeners, response, modelListenerRequest, attributes);
+
                                 return;
                             }
                         }
                     }
                 } catch (Exception e) {
-                    handler.onError(e);
+                    RuntimeException wrappedException = new RuntimeException(e);
+                    onListenError(listeners, wrappedException, modelListenerRequest, responseBuilder.build(), attributes);
```
Comment (langchain4j) [inline langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java]:
```suggestion
                    onListenError(listeners, e, modelListenerRequest, responseBuilder.build(), attributes);
```

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java [hunk 7]
```diff
@@ -164,30 +174,33 @@ public void onResponse(Call<ResponseBody> call, retrofit2.Response<ResponseBody>
...
+
+                    handler.onError(wrappedException);
```
Comment (langchain4j) [inline langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java]:
```suggestion
                    handler.onError(e);
```

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java [hunk 8]
```diff
@@ -111,14 +115,26 @@ public Response<AiMessage> generate(List<ChatMessage> messages, List<ToolSpecifi
...
-        return Response.from(
-                response.getMessage().getToolCalls() != null ?
-                        AiMessage.from(toToolExecutionRequest(response.getMessage().getToolCalls())) :
-                        AiMessage.from(response.getMessage().getContent()),
-                new TokenUsage(response.getPromptEvalCount(), response.getEvalCount())
-        );
+            return response;
+        } catch (Exception e) {
+            RuntimeException wrappedException = new RuntimeException(e);
+            onListenError(listeners, wrappedException, modelListenerRequest, null, attributes);
```
Comment (langchain4j) [inline langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java]:
```suggestion
            onListenError(listeners, e, modelListenerRequest, null, attributes);
```

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java [hunk 9]
```diff
@@ -109,52 +112,59 @@ public void streamingCompletion(CompletionRequest request, StreamingResponseHand
...
+                                );
+                                handler.onComplete(response);
+                                return;
+                            }
                         }
                     }
                 } catch (Exception e) {
-                    handler.onError(e);
+                    RuntimeException wrappedException = new RuntimeException(e);
+                    handler.onError(wrappedException);
```
Comment (langchain4j) [inline langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java]:
```suggestion
                    handler.onError(e);
```

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java [hunk 10]
```diff
@@ -109,52 +112,59 @@ public void streamingCompletion(CompletionRequest request, StreamingResponseHand
...
                 }
             }
 
             @Override
             public void onFailure(Call<ResponseBody> call, Throwable throwable) {
-                handler.onError(throwable);
+                RuntimeException wrappedException = new RuntimeException(throwable);
+                handler.onError(wrappedException);
```
Comment (langchain4j) [inline langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java]:
```suggestion
                handler.onError(throwable);
```

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java [hunk 11]
```diff
@@ -164,30 +174,33 @@ public void onResponse(Call<ResponseBody> call, retrofit2.Response<ResponseBody>
...
                 }
             }
 
             @Override
             public void onFailure(Call<ResponseBody> call, Throwable throwable) {
-                handler.onError(throwable);
+                RuntimeException wrappedException = new RuntimeException(throwable);
+                onListenError(listeners, wrappedException, modelListenerRequest, responseBuilder.build(), attributes);
+
+                handler.onError(wrappedException);
```
Comment (langchain4j) [inline langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java]:
```suggestion
                handler.onError(throwable);
```

File: langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java [hunk 12]
```diff
@@ -164,30 +174,33 @@ public void onResponse(Call<ResponseBody> call, retrofit2.Response<ResponseBody>
...
+
+                    handler.onError(wrappedException);
                 }
             }
 
             @Override
             public void onFailure(Call<ResponseBody> call, Throwable throwable) {
-                handler.onError(throwable);
+                RuntimeException wrappedException = new RuntimeException(throwable);
+                onListenError(listeners, wrappedException, modelListenerRequest, responseBuilder.build(), attributes);
```
Comment (langchain4j) [inline langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java]:
```suggestion
                onListenError(listeners, throwable, modelListenerRequest, responseBuilder.build(), attributes);
```

**Review by ghost — COMMENTED** [review]
I am not sure I understand what is the point to wrap original `Exception`?

**Comment by langchain4j** [comment]
Please update `docs/docs/integrations/language-models/index.md` (add ✅ in Ollama/Observability)

**Comment by Martin7-1** [comment]
> Please update `docs/docs/integrations/language-models/index.md` (add ✅ in Ollama/Observability)

Looks like it's already updated.

> I am not sure I understand what is the point to wrap original Exception?

Perhaps this is indeed redundant, I originally wanted the assert in the test to have generic exception types for comparison, but now I think it's better to just use the original exception. All I need to do in the test is set `expectedExceptionClass()` to `NullPointerException`.

**Review by ghost — APPROVED** [review]
@Martin7-1 thanks a lot!
