### PR TITLE
CohereEmbeddingModel: implement batching

### LINKED ISSUE #1442: [FEATURE] CohereEmbeddingModel: implement batching
`CohereEmbeddingModel` currently sends all `TextSegment` that it receives in `embedAll(List<TextSegment> textSegments)` method to the Cohere API.
When the number of segments is more than 96, Cohere API responds with an error:
`status code: 400; body: {"message":"invalid request: total number of texts must be at most 96 - received 280"}`

We need to add a `maxSegmentsPerBatch` parameter (with default value 96) in the ctor/builder and batch `textSegments`.

### PR DESCRIPTION
**Pull request by Apetun**
## Issue

Closes #1442

## Change

- Added ```DEFAULT_MAX_SEGMENTS_PER_BATCH``` and ```maxSegmentsPerBatch```
- Created ```embedTexts``` function
- Modified ```embedAll``` function and ```getTokenUsage``` function

## General checklist

- [X] There are no breaking changes
- [x] I have added unit and integration tests for my change
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [x] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [x] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [x] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new model integration

- [x] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for adding new embedding store integration

- [x] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [x] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for changing existing embedding store integration

- [x] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by langchain4j** [comment]
@Apetun please add a test where 97 segments are embedded

**Comment by langchain4j** [comment]
@Apetun thanks for the fast implementation 🚀

**Comment by Apetun** [comment]
Added ```should_embed_any_number_of_segments()``` test

File: langchain4j-cohere/src/main/java/dev/langchain4j/model/cohere/CohereEmbeddingModel.java [hunk 1]
```diff
@@ -80,8 +107,8 @@ private static TokenUsage getTokenUsage(EmbedResponse response) {
         if (response.getMeta() != null
                 && response.getMeta().getBilledUnits() != null
                 && response.getMeta().getBilledUnits().getInputTokens() != null) {
-            return new TokenUsage(response.getMeta().getBilledUnits().getInputTokens(), 0);
+            return response.getMeta().getBilledUnits().getInputTokens();
         }
-        return null;
+        return 0;
```
Comment (langchain4j) [inline langchain4j-cohere/src/main/java/dev/langchain4j/model/cohere/CohereEmbeddingModel.java:112]: It does not compile due to these changes, could you please revert?

**Review by ghost — APPROVED** [review]
@Apetun thank you!
