### PR TITLE
Fix #1875: Azure OpenAI: propagate all exceptions in chat models

### LINKED ISSUE #1875: [BUG] Azure OpenAI integration fails to propagate HTTP errors
**Describe the bug**

I am using langchain4j-azure-open-ai in my project. I misconfigured some of the Azure deployment. As a result my chat client started returning the following text to the user: ```Status code 403, "{"error":{"code":"403","message": "Access denied due to Virtual Network/Firewall rules."}}"```

This is obviously nonsensical to show to the user and it is difficult to catch in my code because I'd have to pattern match the output. The implementation should throw an exception instead.

The underlying cause is the exception handling code in `AzureOpenAiChatModel` that swallows the exception and copies the exception message into the response passed to the user: https://github.com/langchain4j/langchain4j/blob/9d42a15ca8fb52d78158d11a429baf2af52528ba/langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java#L319

**Log and Stack trace**

This is the response from Azure HTTP client that caused the issue:
```
HTTP/2 403 
content-type: application/json

{"error":{"code":"403","message": "Access denied due to Virtual Network/Firewall rules."}}
```

**To Reproduce**

Provoke an HTTP error code from Azure OpenAi endpoint, for example by configuring the firewall to reject the errors from your IP.
Call the `@AIService` with any prompt, receive a text response with "Status: 403 ..."

```
@AiService
fun interface LlmIntentRecognitionService {
    @SystemMessage(SYSTEM_MESSAGE)
    fun chat(text: String): String
```

**Expected behavior**

An exception is thrown that is specific to the error code, or an IOException that the caller can catch

This is what is done already in `OpenAiChatModel` here and I wonder if `AzureOpenAiChatModel` could do the same: https://github.com/langchain4j/langchain4j/blob/9d42a15ca8fb52d78158d11a429baf2af52528ba/langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java#L279

**Please complete the following information:**
- LangChain4j version: 0.34
- LLM(s) used: azure-open-ai
- Java version: Coretto-21 JDK
- Spring Boot version (if applicable): 3.3.4

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
## Issue
Paritally fixes #1875

## Change
**This is a breaking change!**

- Changed `AzureOpenAiChatModel`  to propagate **_all_** exceptions thrown from Azure OpenAI SDK to the caller.
- Changed `AzureOpenAiStreamingChatModel`  to propagate **_all_** exceptions thrown from Azure OpenAI SDK to the caller via `StreamingResponseHandler.onError(e)`.
- Changed `AzureOpenAiChatModel` and `AzureOpenAiStreamingChatModel` to propagate **_all_** exceptions thrown from Azure OpenAI SDK via `ChatModelListener.onError(e)`.

## Next Steps
A follow-up PR with similar changes should be submitted for `AzureOpenAiImageModel`, `AzureOpenAiLanguageModel` and `AzureOpenAiStreamingLanguageModel`. `InternalAzureOpenAiHelper.contentFilterManagement()` should be removed. cc @jdubois could you please handle this?

## General checklist
- [ ] There are no breaking changes
- [X] I have added unit and/or integration tests for my change
- [ ] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java [hunk 1]
```diff
@@ -391,13 +401,13 @@ private Response<AiMessage> generate(List<ChatMessage> messages,
             });
 
             return response;
-        } catch (HttpResponseException httpResponseException) {
-            logger.info("Error generating response, {}", httpResponseException.getValue());
+        } catch (Exception exception) {
```
Comment (langchain4j) [inline langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java:404]: Here we catch not just `HttpResponseException` but all exceptions.
This is needed to propagate all types of exceptions to the `ChatModelListener.onError()`, not only `HttpResponseException`.

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java [hunk 2]
```diff
@@ -407,16 +417,8 @@ private Response<AiMessage> generate(List<ChatMessage> messages,
...
-            if (exceptionFinishReason != FinishReason.CONTENT_FILTER) {
-                throw httpResponseException;
-            }
 
-            return Response.from(
-                    aiMessage(httpResponseException.getMessage()),
-                    null,
-                    exceptionFinishReason
-            );
+            throw exception;
```
Comment (langchain4j) [inline langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java:421]: All exceptions will be propagated to the caller as usual instead of returned to the user as a textual response from the LLM

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java [hunk 3]
```diff
@@ -373,19 +364,20 @@ private void asyncCall(ToolSpecification toolThatMustBeExecuted, StreamingRespon
                             logger.warn("Exception while calling model listener", e2);
                         }
                     });
-                    handleResponseException(throwable, handler);
+
+                    handler.onError(throwable);
```
Comment (langchain4j) [inline langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java:368]: same here

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java [hunk 4]
```diff
@@ -449,10 +440,11 @@ private void syncCall(ToolSpecification toolThatMustBeExecuted, StreamingRespons
                     logger.warn("Exception while calling model listener", e2);
                 }
             });
+
+            handler.onError(exception);
```
Comment (langchain4j) [inline langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java:444]: same here

**Comment by langchain4j** [comment]
cc @myrosia

**Review by mariofusco — APPROVED** [review]
This looks ok to me. The only thing that is making the build failing is the violated constraints for the spotless plugin, please run it on the modified classes.

**Comment by langchain4j** [comment]
@mariofusco if I apply spotless, it will introduce so many changes, it will be hard to review

**Comment by mariofusco** [comment]
> @mariofusco if I apply spotless, it will introduce so many changes, it will be hard to review

Agreed. The only alternative that I see for now is disabling it or at least avoid that it makes to fail the build.

**Comment by jdubois** [comment]
OK this is in fact quite simple, I'm waiting for this to be merged and then I'll do the other models.

**Comment by langchain4j** [comment]
@mariofusco @jdubois thank you for the review!
