### PR TITLE
fix #2385

### LINKED ISSUE #2385: [BUG] with AzureOpenAI, Tool not being called if using streaming, even though the API returned a tool to be called
**Describe the bug**
a similar issue to https://github.com/langchain4j/langchain4j/issues/1853 may exist in the langchain-azure-openai component

**Log and Stack trace**

<details>
<summary>execution logs </summary>

```
15:18:54.322 [main] INFO com.azure.ai.openai.implementation.OpenAIClientImpl$OpenAIClientService.getChatCompletions -- {"az.sdk.message":"HTTP request","method":"POST","url":"https://***.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2024-10-01-preview","tryCount":1,"Date":"Thu, 09 Jan 2025 07:18:54 GMT","x-ms-client-request-id":"467b58c3-8679-4c74-94bd-019a9125209d","Accept":"application/json","User-Agent":"langchain4j-azure-openai","redactedHeaders":"api-key,Content-Type","content-length":676,"body":"{\"tools\":[{\"function\":{\"name\":\"query_temperatures\",\"description\":\"args: start_time, end_time, in the format of yyyy-MM-dd, e.g. 20250108\\nreturn temperatures from start time to end time\",\"parameters\":{\"type\":\"object\",\"properties\":{\"startDate\":{\"type\":\"string\"},\"endDate\":{\"type\":\"string\"}},\"required\":[\"startDate\",\"endDate\"]}},\"type\":\"function\"}],\"messages\":[{\"content\":\"you are a helpful assitant. you must show your thoughts before calling any tool. today: 2025-01-09\\n\",\"role\":\"system\"},{\"role\":\"user\",\"content\":\"show temparature data in recent 3 months, output current date, query time and result\"}],\"max_tokens\":3000,\"temperature\":0.7,\"stream\":true,\"model\":\"gpt-4o-mini\"}"}
15:18:56.523 [reactor-http-nio-1] INFO com.azure.ai.openai.implementation.OpenAIClientImpl$OpenAIClientService.getChatCompletions -- {"az.sdk.message":"HTTP response","statusCode":200,"url":"https://***.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2024-10-01-preview","durationMs":2203,"Date":"Thu, 09 Jan 2025 07:18:55 GMT","Transfer-Encoding":"chunked","x-ms-client-request-id":"467b58c3-8679-4c74-94bd-019a9125209d","redactedHeaders":"x-request-id,x-ms-region,x-envoy-upstream-service-time,apim-request-id,x-ratelimit-remaining-tokens,x-ratelimit-remaining-requests,Strict-Transport-Security,azureml-model-session,x-accel-buffering,x-content-type-options,x-ms-rai-invoked,Content-Type"}
emit: 
emit: To
emit:  obtain
emit:  the
emit:  temperature
emit:  data
emit:  for
emit:  the
emit:  past
emit:  three
emit:  months
emit: ,
emit:  I
emit:  need
emit:  to
emit:  calculate
emit:  the
emit:  start
emit:  and
emit:  end
emit:  dates
emit:  for
emit:  the
emit:  query
emit: .
emit:  


emit: Today's
emit:  date
emit:  is
emit:  January
emit:  
emit: 9
emit: ,
emit:  
emit: 202
emit: 5
emit: .
emit:  The
emit:  past
emit:  three
emit:  months
emit:  would
emit:  be
emit:  from
emit:  October
emit:  
emit: 9
emit: ,
emit:  
emit: 202
emit: 4
emit: ,
emit:  to
emit:  January
emit:  
emit: 9
emit: ,
emit:  
emit: 202
emit: 5
emit: .


emit: I'll
emit:  format
emit:  the
emit:  dates
emit:  accordingly
emit: :

emit: -
emit:  Start
emit:  Date
emit: :
emit:  
emit: 202
emit: 4
emit: -
emit: 10
emit: -
emit: 09
emit: 

emit: -
emit:  End
emit:  Date
emit: :
emit:  
emit: 202
emit: 5
emit: -
emit: 01
emit: -
emit: 09
emit: 


emit: Now
emit: ,
emit:  I
emit:  will
emit:  call
emit:  the
emit:  temperature
emit:  query
emit:  function
emit:  with
emit:  these
emit:  dates
emit: .
emit:  After
emit:  obtaining
emit:  the
emit:  data
emit: ,
emit:  I
emit:  will
emit:  output
emit:  the
emit:  current
emit:  date
emit: ,
emit:  query
emit:  time
emit: ,
emit:  and
emit:  the
emit:  results
emit: .
emit:  


emit: Let's
emit:  proceed
emit:  to
emit:  query
emit:  the
emit:  temperature
emit:  data
emit: .
================ complete response start ===============
AiMessage { text = "To obtain the temperature data for the past three months, I need to calculate the start and end dates for the query. 

Today's date is January 9, 2025. The past three months would be from October 9, 2024, to January 9, 2025.

I'll format the dates accordingly:
- Start Date: 2024-10-09
- End Date: 2025-01-09

Now, I will call the temperature query function with these dates. After obtaining the data, I will output the current date, query time, and the results. 

Let's proceed to query the temperature data." toolExecutionRequests = null }
================ complete response end ===============
```

</details>

No tool execution request is executed by the langchiain4j code.  Event a tool call request is returned, see the logs below that is produced by executing the same request using curl

<details>

<summary> curl output log </summary>

```
data: {"choices":[],"created":0,"id":"","model":"","object":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"jailbreak":{"filtered":false,"detected":false},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"choices":[{"content_filter_results":{},"delta":{"content":"","refusal":null,"role":"assistant"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"To"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" retrieve"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" the"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" temperature"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" data"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" for"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" the"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" recent"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" three"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" months"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":","},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" I"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" will"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" calculate"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" the"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" start"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" and"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" end"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" dates"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" for"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" the"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" query"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":":\n\n"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"-"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" Current"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" date"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":":"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" January"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" "},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"9"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":","},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" "},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"202"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"5"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"\n"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"-"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" Start"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" date"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":":"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" October"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" "},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"9"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":","},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" "},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"202"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"4"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" ("},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"3"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" months"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" before"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" January"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" "},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"9"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":","},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" "},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"202"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"5"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":")\n"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"-"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" End"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" date"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":":"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" January"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" "},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"9"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":","},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" "},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"202"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"5"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" ("},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"current"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" date"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":")\n\n"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"I"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" will"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" now"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" prepare"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" to"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" query"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" the"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" temperature"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" data"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" for"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" this"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" period"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"."},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" \n\n"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"Let's"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" proceed"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" with"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" the"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" query"},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"."},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"","name":"query_temperatures"},"id":"call_fERiFnP6UAXKAQYgWEouQlHT","index":0,"type":"function"}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"{\""},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"start"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"Date"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"\":\""},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"202"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"4"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"-"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"10"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"-"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"09"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"\",\""},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"end"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"Date"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"\":\""},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"202"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"5"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"-"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"01"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"-"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"09"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{"tool_calls":[{"function":{"arguments":"\"}"},"index":0}]},"finish_reason":null,"index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: {"choices":[{"content_filter_results":{},"delta":{},"finish_reason":"tool_calls","index":0,"logprobs":null}],"created":1736407895,"id":"chatcmpl-AnhIt2rw8vL8czymkCwEOKKTg7HPc","model":"gpt-4o-mini-2024-07-18","object":"chat.completion.chunk","system_fingerprint":"fp_5154047bf2"}

data: [DONE]
```

</details>

**To Reproduce**
```java
public static void main(String[] _args) throws Exception {
        // String res = Models.chatModel().generate("hello");
        // System.out.println(res);

        MessageWindowChatMemory memory = 
            MessageWindowChatMemory
            .builder()
            .maxMessages(100)
            .build();

        HelpfulAssistant helper = AiServices.builder(HelpfulAssistant .class)
            .streamingChatLanguageModel(Models.streamChatModel() /* :AzureOpenAiStreamingChatModel */)
            .chatLanguageModel(Models.chatModel()/* : */)
            .chatMemory(memory)
            .tools(new Tools())
            .build();

        TokenStream res = helper.askStreaming("show temparature data in recent 3 months, output current date, query time and result");
        res.onNext(s->{
            System.out.println("emit: " + s);
         });
        res.onComplete(res2->{
            System.out.println("================ complete response start ===============");
            System.out.println(res2.content());
            System.out.println("================ complete response end ===============");
        });
        res.onError(e->{
            System.out.println("error: " + e);
        });
        res.start();

        Thread.sleep(20000);

        // System.out.println(helper.ask("show temparature data in recent 3 months, output current date, query time and result"));
    }

    interface HelpfulAssistant {
        @SystemMessage("""
        you are a helpful assitant. you must show your thoughts before calling any tool. today: 2025-01-09
        """)
        TokenStream askStreaming(String question);
        @SystemMessage("""
        you are a helpful assitant. you must show your thoughts before calling any tool. today: 2025-01-09
        """)
        String ask(String question);
    }

    static class Tools {

        @Tool(name="query_temperatures", value="""
        args: start_time, end_time, in the format of yyyy-MM-dd, e.g. 20250108
        return temperatures from start time to end time """)
        List<Integer> queryTemperatures(String startDate, String endDate) {
            System.out.println("start_date: " + startDate + ", end_date: "+ endDate);
            return List.of(1,2,3,3,5);
        }
    }
```

**Expected behavior**
the tool should be executed (as returned by the non-streaming ask method)

```
Here is the temperature data retrieved for the recent 3 months:

- **Current Date:** 2025-01-09
- **Query Time:** From 2024-10-09 to 2025-01-09
- **Temperature Data:** [1, 2, 3, 3, 5]
```

**Please complete the following information:**
- LangChain4j version: 1.0.0-alpha1
- LLM(s) used: gpt-4o-mini
- Java version: 17
- Spring Boot version (if applicable): 

**Additional context**

### PR DESCRIPTION
**Pull request by paulluap**
## Issue
Fixes #2385

## Change
create AIMessage with both content and tool call requests when both are present in streaming response.

## General checklist
- [x] There are no breaking changes
- [ ] I have added unit and/or integration tests for my change
- [ ] The tests cover both positive and negative cases
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java [hunk 1]
```diff
@@ -126,13 +126,10 @@ public void append(Completions completions) {
...
-            return Response.from(
-                    AiMessage.from(content),
-                    tokenUsage(content, tokenizer),
-                    finishReasonFrom(finishReason)
-            );
-        }
+        TokenUsage contentDeltaOutTokenUsage = 
+            !content.isEmpty() ?
+                tokenUsage(content, tokenizer):
+                new TokenUsage(0,0);
```
Comment (dliubarskyi) [inline langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java:132]: why `new TokenUsage(0,0)`? Even if `content` is empty, token usage can be positive, because tool calling also counts towards token usage

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java [hunk 2]
```diff
@@ -141,8 +138,10 @@ public Response<AiMessage> build(Tokenizer tokenizer, boolean forcefulToolExecut
                     .arguments(toolArgumentsBuilder.toString())
                     .build();
             return Response.from(
-                    AiMessage.from(toolExecutionRequest),
-                    tokenUsage(singletonList(toolExecutionRequest), tokenizer, forcefulToolExecution),
+                    !content.isEmpty() ?
+                        AiMessage.from(content, singletonList(toolExecutionRequest)) :
+                        AiMessage.from(toolExecutionRequest),
+                    tokenUsage(singletonList(toolExecutionRequest), tokenizer, forcefulToolExecution).add(contentDeltaOutTokenUsage),
```
Comment (dliubarskyi) [inline langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java:144]: Please explain why adding token usages is required? We should just pass token usage returned by Azure SDK as-is, without any additional calculations

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java [hunk 3]
```diff
@@ -156,12 +155,22 @@ public Response<AiMessage> build(Tokenizer tokenizer, boolean forcefulToolExecut
                             .build())
                     .collect(toList());
             return Response.from(
-                    AiMessage.from(toolExecutionRequests),
-                    tokenUsage(toolExecutionRequests, tokenizer, forcefulToolExecution),
+                    !content.isEmpty() ?
+                        AiMessage.from(content, toolExecutionRequests) :
+                        AiMessage.from(toolExecutionRequests),
+                    tokenUsage(toolExecutionRequests, tokenizer, forcefulToolExecution).add(contentDeltaOutTokenUsage),
```
Comment (dliubarskyi) [inline langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java:161]: same here

Comment (dliubarskyi) [inline langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java:161]: same here

**Review by dliubarskyi — COMMENTED** [review]
@paulluap thank you! Please add an integration test to make sure it works as expected.

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java (hunk 1 above)
Comment (paulluap) [reply langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java:132]: Hi, @dliubarskyi , thanks for reviewing, [the code before this change](https://github.com/langchain4j/langchain4j/blob/cdf818c0d9f18a3aec4e96bc2eecce2cc1342ca9/langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java#L130) counts either content token or tool request token, this change adds additional content token usage `contentDeltaOutTokenUsage` if there is any,  for example, some step by step thoughts in addition to tool cal requests.

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java (hunk 2 above)
Comment (paulluap) [reply langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java:144]: The current implemention computes token usage without using the SDK returned usage, on top of which this fix is based. I agree we should use the returned token usage (at the time being I do not have the much time to further verify and provide a better fix)

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java (hunk 3 above)
Comment (paulluap) [reply langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java:161]: please see the response above.

Comment (paulluap) [reply langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java:161]: please see the response above.

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java (hunk 2 above)
Comment (dliubarskyi) [reply langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java:144]: Oh, now I see it. Yes, we should not use `Tokenizer` but use the token usage returned by the SDK, there is actually an issue for this: https://github.com/langchain4j/langchain4j/issues/1068

**Comment by dliubarskyi** [comment]
@paulluap would it be possible to add a reproducible test to make sure the bug we are fixing is fixed?

File: langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java (hunk 1 above)
Comment (dliubarskyi) [reply langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java:132]: Thanks, makes sense!

**Review by dliubarskyi — APPROVED** [review]
@paulluap thanks a lot!
