### PR TITLE
Fix anthropic token count estimator empty messages

### LINKED ISSUE #3764: [BUG] AnthropicTokenCountEstimator send request with wrong format
**Describe the bug**
Seems like the API for the token counting expects a request with a "messages" field.

**Log and Stack trace**
```
dev.langchain4j.exception.HttpException: {"type":"error","error":{"type":"invalid_request_error","message":"messages: Field required"},"request_id":"req_011CTX49xh2zg8aK6YTHUF6V"}
	at dev.langchain4j.http.client.jdk.JdkHttpClient.execute(JdkHttpClient.java:53)
	at dev.langchain4j.http.client.log.LoggingHttpClient.execute(LoggingHttpClient.java:48)
	at dev.langchain4j.model.anthropic.internal.client.DefaultAnthropicClient.countTokens(DefaultAnthropicClient.java:397)
	at dev.langchain4j.model.anthropic.AnthropicTokenCountEstimator.estimateTokenCountInMessages(AnthropicTokenCountEstimator.java:84)
	at dev.langchain4j.memory.chat.TokenWindowChatMemory.ensureCapacity(TokenWindowChatMemory.java:87)
	at dev.langchain4j.memory.chat.TokenWindowChatMemory.add(TokenWindowChatMemory.java:70)
```

**To Reproduce**
Create an Assistant with AiServices like in the example below. Then just call chat method with some random message.
```
public interface Assistant {
  Result<String> chat(@MemoryId String memoryId, @UserMessage String userMessage);
}

ChatModel chatModel = AnthropicChatModel.builder()
				.apiKey(Config.getApiKey())
				.modelName(agentConfig.getModel())
				.temperature(agentConfig.getTemperature())
				.topP(agentConfig.getTopP())
				.timeout(Duration.ofSeconds(Config.getApiTimeout()))
                                .logRequests(true)
                                .logResponses(true)
				.build();

TokenCountEstimator estimator = AnthropicTokenCountEstimator.builder()
				.modelName(AnthropicChatModelName.valueOf(agentConfig.getModel())) //Maybe make this builder method to accept String arguments as well
				.apiKey(Config.getApiKey())
                                .logRequests(true)
                                .logResponses(true)
				.build();

Assistant assistant = AiServices.builder(Assistant.class)
            .chatModel(chatModel)
            .systemMessageProvider(o -> "You are a useful assistant")
            .chatMemoryProvider(memoryId -> TokenWindowChatMemory.withMaxTokens(getMaxTokens(), estimator))
            .build();
```

**Expected behavior**
I expect to receive an actual response from the chat method call.

**Please complete the following information:**
- LangChain4j version: 1.5
- LLM(s) used: claude-3-7-sonnet-20250219, claude-3-haiku-20240307
- Java version: 21
- Spring Boot version (if applicable): 

**Additional context**
This is the request that HTTP Client sends
```
[INFO ] 2025-09-26 16:01:04,895 [http-nio-7200-exec-2 | d.l.h.c.l.LoggingHttpClient] HTTP request:
- method: POST
- url: https://api.anthropic.com/v1/messages/count_tokens
- headers: [x-api-key: sk-an...AA], [anthropic-version: 2023-06-01], [Content-Type: application/json]
- body: {
  "model" : "claude-3-haiku-20240307",
  "system" : [ {
    "type" : "text",
    "text" : "You are a useful assistant"
  } ]
}
```

### PR DESCRIPTION
**Pull request by HamzaElzarw-2022**
fixes #3764

### CODE REVIEW

**Comment by HamzaElzarw-2022** [comment]
Hello @dliubarskyi, can you please review this PR when you have time.

File: langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicTokenCountEstimator.java [hunk 1]
```diff
@@ -42,6 +44,8 @@ public AnthropicTokenCountEstimator(Builder builder) {
                 .build();
 
         this.modelName = ensureNotBlank(builder.modelName, "modelName");
+        this.addDummyUserMessageIfNoUserMessages = Boolean.TRUE.equals(builder.addDummyUserMessageIfNoUserMessages);
```
Comment (dliubarskyi) [inline langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicTokenCountEstimator.java:47]: I guess we should have false by default to keep existing logic intact, WDYT?

**Review by dliubarskyi — COMMENTED** [review]
@HamzaElzarw-2022 thanks!

File: langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicTokenCountEstimator.java (hunk 1 above)
Comment (HamzaElzarw-2022) [reply langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicTokenCountEstimator.java:47]: Yes, that's what we already have. The `builder.addDummyUserMessageIfNoUserMessages` is null by default which resolves to false, unless the user explicitly calls `builder.addDummyUserMessageIfNoUserMessages("dummy message")`. or call it without passing any arguments so the dummy message defaults to "ping".

**Comment by HamzaElzarw-2022** [comment]
Hello @dliubarskyi, Do we need any changes for this PR?

File: langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicTokenCountEstimator.java (hunk 1 above)
Comment (dliubarskyi) [reply langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicTokenCountEstimator.java:47]: Right, I was confused by `TRUE`

**Review by dliubarskyi — APPROVED** [review]
@HamzaElzarw-2022 thank you!
