### PR TITLE
#3588: Handle IllegalArgumentException during URI.create

### LINKED ISSUE #3588: [BUG] Unhandled IllegalArgumentException on GoogleCustomWebSearchEngine
**Describe the bug**
When mapping links contained in `com.google.api.services.customsearch.v1` models coming from Google PSE (https://www.googleapis.com/customsearch/v1) responses, `URI.create` is executed in several places (result links, image links, thumbnail links) without encoding the string and without capturing `IllegalArgumentException`. As a consequence, result items could be missed, and the exception interrupts the entire processing.

We should:

1. Handle the links appropriately before executing URI.create. 
2. Catch the exception for the failing item and continue processing.

**Log and Stack trace**
```
Error during web search with dev.langchain4j.web.search.google.customsearch.GoogleCustomWebSearchEngine@5cc9655b at start index 1: Illegal character in query at index 72: https://www.golfargentino.com/products/?search=taylormade&price_regular={745000,1762500} 
```

**To Reproduce**
Any resulting query that might contain unsupported characters such as { or } ends up in the error logs. For example, I performed the search query driver golf taylormade qi35 specifically on the site https://golfargentino.com. Which resulted on: `https://www.golfargentino.com/products/?search=taylormade&price_regular={745000,1762500}`
This can also be reproduced with a simple mock in unit tests.

**Expected behavior**
String links should be encoded before calling URI.create, and in case of an IllegalArgumentException, we should continue processing the remaining items without interrupting the overall process.

**Please complete the following information:**
- LangChain4j version: 1.3.0 & 1.3.0-beta9 for langchain4j-web-search-engine-google-custom
- LLM(s) used: gemini-1.5-flash
- Java version: 21
- Spring Boot version (if applicable): 3.4.3

### PR DESCRIPTION
**Pull request by msampietro**
## Issue

Fixes #3588

## Change
This PR fixes URI creation safety by replacing direct URI constructors with the createUriSafely() utility method to prevent crashes from malformed URLs returned by Google's API.

Changes Made:

Safe URI creation for image search results (imageLink, contextLink, thumbnailLink)
Safe URI creation for organic search results
Added static import for createUriSafely utility (introduced in separate class)
Prevents IllegalArgumentException and applied fallback when Google API returns invalid URL strings, making the search mapping more robust.

## General checklist

- [x] There are no breaking changes
- [x] I have added unit and/or integration tests for my change
- [x] The tests cover both positive and negative cases
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by msampietro** [comment]
I believe failing checks are unrelated to the committed changes

File: web-search-engines/langchain4j-web-search-engine-google-custom/src/main/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomWebSearchUtils.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
+package dev.langchain4j.web.search.google.customsearch;
+
+import java.net.URI;
+import java.nio.charset.StandardCharsets;
+import java.util.BitSet;
+
+/**
+ * Utility class for Google Custom Web Search operations.
+ */
+public final class GoogleCustomWebSearchUtils {
```
Comment (dliubarskyi) [inline web-search-engines/langchain4j-web-search-engine-google-custom/src/main/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomWebSearchUtils.java]:
```suggestion
final class GoogleCustomWebSearchUtils {
```

Comment (msampietro) [reply web-search-engines/langchain4j-web-search-engine-google-custom/src/main/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomWebSearchUtils.java]: Thanks @dliubarskyi for the review and commit! Anything else required for an approval?

**Review by dliubarskyi — APPROVED** [review]
@msampietro thank you!
