### PR TITLE
fix: add null/empty choices guard in OpenAiChatModel and aiMessageFrom

### LINKED ISSUE #4810: [BUG] OpenAiChatModel and OpenAiUtils.aiMessageFrom() crash when choices is null or empty
## Describe the bug

`OpenAiChatModel.doChat()` accesses `openAiResponse.choices().get(0)` at line 162 without checking if `choices()` is null or empty. Additionally, the shared utility `OpenAiUtils.aiMessageFrom()` does the same at line 346.

When the OpenAI API returns a response with no choices (e.g. content filtering, malformed response, partial failure), this causes:
- `NullPointerException` if `choices()` is null
- `IndexOutOfBoundsException` if `choices()` is an empty list

The streaming counterpart `OpenAiStreamingChatModel` already has this guard (line 188-189):
```java
List<ChatCompletionChoice> choices = partialResponse.choices();
if (isNullOrEmpty(choices)) { return; }
```

## Log and Stack trace

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
    at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:XXX)
    at dev.langchain4j.model.openai.OpenAiChatModel.doChat(OpenAiChatModel.java:162)
```

## How To Reproduce

Send a request via `OpenAiChatModel` that results in the API returning an empty choices list.

## Expected behavior

The model should throw a clear `IllegalArgumentException` with a descriptive message instead of a cryptic `IndexOutOfBoundsException` or `NullPointerException`.

## Environment
- Langchain4j version: 1.0.0-beta1+
- Java version: 17+
- Spring Boot version: N/A

### PR DESCRIPTION
**Pull request by farzad-sedaghatbin**
## Issue
Closes #4810

## Change
Added null/empty guard for `choices` in two places:

1. **`OpenAiChatModel.doChat()`** — added `isNullOrEmpty(openAiResponse.choices())` check before accessing `.get(0)`, throwing `IllegalArgumentException` with a descriptive message.

2. **`OpenAiUtils.aiMessageFrom()`** — added the same guard in this shared utility method which also accessed `choices().get(0)` without protection.

Both are consistent with the streaming counterpart `OpenAiStreamingChatModel` which already has `isNullOrEmpty(choices)` guard at line 188-189.

## General checklist
- [X] There are no breaking changes (API, behaviour)
- [X] I have added unit and/or integration tests for my change
- [X] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [X] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

File: langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/OpenAiUtils.java [hunk 1]
```diff
@@ -343,6 +341,9 @@ public static AiMessage aiMessageFrom(ChatCompletionResponse response) {
     }
 
     public static AiMessage aiMessageFrom(ChatCompletionResponse response, boolean returnThinking) {
+        if (isNullOrEmpty(response.choices())) {
+            throw illegalArgument("Chat completion failed: no choices returned");
```
Comment (dliubarskyi) [inline langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/OpenAiUtils.java]: I am not sure this is a right solution for "e.g. content filtering, malformed response, partial failure"

For content filtering we have a `ContentFilteredException`, for other cases we need to check which exactly exception to throw.

Comment (farzad-sedaghatbin) [reply langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/OpenAiUtils.java]: Thanks for the review feedback! @dliubarskyi  I investigated the actual runtime scenarios where `choices` would be null/empty in a 200 OK response:

1. **Content filtering at prompt level** → Already caught as HTTP 400 → `InvalidRequestException` (before choices are ever accessed)
2. **Content filtering at output level** → A choice IS returned with `finish_reason: "content_filter"` — choices is NOT empty
3. **Refusal (structured outputs)** → A choice IS returned with `refusal` field → already throws `ContentFilteredException`
4. **Malformed/unexpected response** → The only case where choices is actually empty in a 200, and there's no distinguishing info in the parsed response

So the guard is really only for case #4 — an unexpected server response where we get 200 OK but no choices and no indication why. The current `ChatCompletionResponse` model doesn't carry `prompt_filter_results` or any other field that would let us distinguish causes (they're dropped by `@JsonIgnoreProperties(ignoreUnknown = true)`).

What exception type would you prefer for this scenario? Options I see:

- `LangChain4jException` — generic base, non-retriable
- `InternalServerException` — "server did something wrong" (though technically not an HTTP error)
- Something else?

Or would you prefer a different approach entirely (e.g., removing the guard and letting the raw `IndexOutOfBoundsException` propagate)?

Comment (dliubarskyi) [reply langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/OpenAiUtils.java]: Thank you for the analysis, let's go with `InternalServerException` then

**Comment by farzad-sedaghatbin** [comment]
fixed

**Review by dliubarskyi — APPROVED** [review]
@farzad-sedaghatbin thank you!
