### PR TITLE
#3628: Use received description for visited json object schema

### LINKED ISSUE #3628: [BUG] Description is reused for a tool parameter from a custom class
**Describe the bug**
[`JsonSchemaElementUtils`](https://github.com/langchain4j/langchain4j/blob/e900f3f718e2196ce9aa9e6082351cc9ee850590/langchain4j-core/src/main/java/dev/langchain4j/internal/JsonSchemaElementUtils.java#L38) is used to define the parameters of a tool (among other functionalities). However, the method [`jsonObjectOrReferenceSchemaFrom`](https://github.com/langchain4j/langchain4j/blob/e900f3f718e2196ce9aa9e6082351cc9ee850590/langchain4j-core/src/main/java/dev/langchain4j/internal/JsonSchemaElementUtils.java#L98) reuses the description of a `JsonObject` already defined/visited. Thus, this can cause issues when calling the tool with the right parameters.

**To Reproduce**
Create a tool with two parameters with the same POJO (e.g., Place) and observe how the description is reused. For example, in this case, both parameters (`origin` and `destination`) will have the description `origin place`.

```
  @Tool(
      name = "getDestinations",
      value = "Get a list of recommended destinations with flight prices and images")
  public ToolResponse<List<Destination>> getDestinations(
      @P(value = "origin place") Place origin,
      @P(value = "destination place") Place destination) {
}
```

**Expected behavior**
The description should be unique and updated in the reused [JsonSchemaElement](https://github.com/langchain4j/langchain4j/blob/e900f3f718e2196ce9aa9e6082351cc9ee850590/langchain4j-core/src/main/java/dev/langchain4j/internal/JsonSchemaElementUtils.java#L107)

**Please complete the following information:**
- LangChain4j version: 1.4.0
- LLM(s) used: -
- Java version: 21
- Spring Boot version (if applicable): No

### PR DESCRIPTION
**Pull request by jordibisbal8**
## Issue
Fixes #3628 

## Change
In this PR, we aim to return the received description instead of using the one from the visited `JsonObjectSchema`. For this, we need to build a new `JsonObjectSchema` with all properties from the visited one, but with the received description.

## General checklist
- [x] There are no breaking changes
- [x] I have added unit and/or integration tests for my change
- [x] The tests cover both positive and negative cases
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

File: langchain4j-core/src/main/java/dev/langchain4j/internal/JsonSchemaElementUtils.java [hunk 1]
```diff
@@ -107,6 +100,19 @@ public static JsonSchemaElement jsonObjectOrReferenceSchemaFrom(
             if (jsonSchemaElement instanceof JsonReferenceSchema) {
                 visitedClassMetadata.recursionDetected = true;
             }
+            if (jsonSchemaElement instanceof JsonObjectSchema obj) {
+                if (Objects.equals(description, obj.description())) {
+                    return obj;
+                }
+                return JsonObjectSchema.builder()
```
Comment (dliubarskyi) [inline langchain4j-core/src/main/java/dev/langchain4j/internal/JsonSchemaElementUtils.java]: nit: if/when new field(s) will be added to `JsonObjectSchema` in the future, there is a high probability that we will forget to update this place. Basically, here you want to make a copy of `JsonObjectSchema`, only overriding the description. What about adding a `JsonObjectSchema.toBuilder()` method that will return builder will all fields prefilled, then you will be able to do:
`return obj.toBuilder().description(description).build();`

WDYT?

File: langchain4j-core/src/test/java/dev/langchain4j/internal/JsonSchemaElementUtilsTest.java [hunk 2]
```diff
@@ -136,6 +133,37 @@ void should_use_non_null_description_for_uuid() {
                         .build());
     }
 
+    @Test
+    void givenVisitedJsonObjectSchema_whenDescriptionIsDifferent_thenReturnsNewSchemaWithUpdatedDescription() {
```
Comment (dliubarskyi) [inline langchain4j-core/src/test/java/dev/langchain4j/internal/JsonSchemaElementUtilsTest.java:137]: nice tests, although I would also add an integration test that defines tool with `@Tool` and verifies that all pieces work well together

**Review by dliubarskyi — COMMENTED** [review]
@jordibisbal8 good job, thank you!

File: langchain4j-core/src/main/java/dev/langchain4j/internal/JsonSchemaElementUtils.java (hunk 1 above)
Comment (jordibisbal8) [reply langchain4j-core/src/main/java/dev/langchain4j/internal/JsonSchemaElementUtils.java]: Sounds good, similar to the `toBuilder()` from Lombok, although I have seen that we should not use it. Let me do the changes :)

File: langchain4j-core/src/test/java/dev/langchain4j/internal/JsonSchemaElementUtilsTest.java (hunk 2 above)
Comment (jordibisbal8) [reply langchain4j-core/src/test/java/dev/langchain4j/internal/JsonSchemaElementUtilsTest.java:137]: Sure! Should I add it under[ this test](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-core/src/test/java/dev/langchain4j/agent/tool/ToolSpecificationsTest.java)? I have tested it locally, but an additional IT never hurts.

File: langchain4j-core/src/main/java/dev/langchain4j/internal/JsonSchemaElementUtils.java (hunk 1 above)
Comment (jordibisbal8) [reply langchain4j-core/src/main/java/dev/langchain4j/internal/JsonSchemaElementUtils.java]: https://github.com/langchain4j/langchain4j/pull/3661/commits/1f9cfeb5f368097b3ac7ffe30ea6804868acc67e

File: langchain4j-core/src/test/java/dev/langchain4j/internal/JsonSchemaElementUtilsTest.java (hunk 2 above)
Comment (jordibisbal8) [reply langchain4j-core/src/test/java/dev/langchain4j/internal/JsonSchemaElementUtilsTest.java:137]: https://github.com/langchain4j/langchain4j/pull/3661/commits/67c2dde9145a59504c75f8c0d2603f74d87b4f97

File: langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/json/JsonObjectSchema.java [hunk 3]
```diff
@@ -53,6 +50,15 @@ public static Builder builder() {
         return new Builder();
     }
 
+    public Builder toBuilder() {
+        return builder()
+                .description(this.description)
+                .addProperties(this.properties)
+                .required(this.required != null ? new ArrayList<>(this.required) : null)
```
Comment (jordibisbal8) [inline langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/json/JsonObjectSchema.java:57]: Need to make a defensive copy, not to use the original list

**Review by dliubarskyi — APPROVED** [review]
@jordibisbal8 thanks a lot, great job!
