### PR TITLE
[BUG] DefaultAiServices creates new ExecutorService per instance causing resource leak

### LINKED ISSUE #4343: [BUG] DefaultAiServices creates new ExecutorService per instance causing resource leak
**Describe the bug**
`DefaultAiServices.build()` creates a new `ExecutorService` for each instance that is never shut down, causing resource leaks.

**Affected method:**
- `DefaultAiServices.build()` (line 108)

**Log and Stack trace**
N/A

**To Reproduce**

```java
// DefaultAiServices.build() (line 108)
private final ExecutorService executor = Executors.newCachedThreadPool();
```

**Expected behavior**
Use the shared global executor from `DefaultExecutorProvider.getDefaultExecutorService()` to prevent resource leaks.

**Expected fix:**
```java
private final ExecutorService executor = DefaultExecutorProvider.getDefaultExecutorService();
```

**Please complete the following information:**
- LangChain4j version: Latest main branch
- LLM(s) used: N/A
- Java version: Java 21
- Spring Boot version (if applicable): N/A

### PR DESCRIPTION
**Pull request by thswlsqls**
## Issue
Closes #4343

## Change
Replaced `Executors.newCachedThreadPool()` with `DefaultExecutorProvider.getDefaultExecutorService()` in `DefaultAiServices.build()` to use the shared global executor and prevent resource leaks.

## General checklist
- [X] There are no breaking changes (API, behaviour)
- [ ] I have added unit and/or integration tests for my change
- [ ] The tests cover both positive and negative cases
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module
- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration
- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

File: langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java [hunk 1]
```diff
@@ -105,7 +105,7 @@ public T build() {
                 new Class<?>[] {context.aiServiceClass},
                 new InvocationHandler() {
 
-                    private final ExecutorService executor = Executors.newCachedThreadPool();
+                    private final ExecutorService executor = DefaultExecutorProvider.getDefaultExecutorService();
```
Comment (dliubarskyi) [inline langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java]: This executor is used only when `@Moderate` annotation is present. What about improving it one step further and creating it lazily only when `@Moderate` is present?

**Review by dliubarskyi — COMMENTED** [review]
@thswlsqls thank you!

**Comment by thswlsqls** [comment]
@dliubarskyi Thank you for the suggestion! I've implemented lazy initialization.

**Review by dliubarskyi — APPROVED** [review]
@thswlsqls thank you!
