### PR TITLE
Fix #1124: preserve metadata during query compression

### LINKED ISSUE #1124: [BUG] Query metadata are lost when using the query compression technique
Hi

I have created an assistant using a EmbeddingStoreContentRetriever based on a dynamic metadata filter, like this:

Function<Query, Filter> filterByUserId =
                (query) -> metadataKey("userId").isEqualTo(query.metadata().chatMemoryId().toString());

(https://github.com/langchain4j/langchain4j-examples/blob/main/rag-examples/src/main/java/_3_advanced/_05_Advanced_RAG_with_Metadata_Filtering_Examples.java)

The filter works fine, but when I added a query compression step, and I chat to the assistant for the second time, it fails because query.metadata() is always null. It seems that during query compression, the metadata of the query are missing.  

- LangChain4j version: 0.30
- LLM(s) used:  LLama3
- Java version:  21
- Spring Boot version: 3.2.4 

thanks

### PR DESCRIPTION
**Pull request by ghost**
Fixes #1124

This pull request addresses the issue of query metadata being lost during passing it through the `CompressingQueryTransformer` and `ExpandingQueryTransformer`.

### CODE REVIEW

File: langchain4j-core/src/main/java/dev/langchain4j/rag/query/transformer/CompressingQueryTransformer.java [hunk 1]
```diff
@@ -72,7 +72,7 @@ public Collection<Query> transform(Query query) {
 
         Prompt prompt = createPrompt(query, format(chatMemory));
         String compressedQuery = chatLanguageModel.generate(prompt.text());
-        return singletonList(Query.from(compressedQuery));
+        return singletonList(Query.from(compressedQuery, query.metadata()));
```
Comment (langchain4j) [inline langchain4j-core/src/main/java/dev/langchain4j/rag/query/transformer/CompressingQueryTransformer.java]: Fix the same for expanding query transformer
