### PR TITLE
AzureAiSearchEmbeddingStore with index creation

### LINKED ISSUE #1249: [Bug] AzureAiSearchEmbeddingStore with index creation
Hi,

I'm facing with an error when I use AzureAiSearchEmbeddingStore to create an index (for ingesting doc with EmbeddingStoreIngestor).
In my usecase, I've want to have 1 index per language. 

How to reproduce: 
- create a AzureAiSearchEmbeddingStore with createOrUpate at true. Here a sample of code
```
@Component
public class EmbeddingsStoreProvider {
    private SearchEnvProperties envSearch;
    private Template indexTemplate;

    public EmbeddingsStoreProvider(SearchEnvProperties envSearch, Template indexTemplate) {
        this.envSearch = envSearch;
        this.indexTemplate = indexTemplate;
    }

    public EmbeddingStore<TextSegment> create(String searchIndexName) throws Exception {
        Map<String, String> model = new HashMap<>();
        model.put("name", searchIndexName);
        String indexJson = FreeMarkerTemplateUtils.processTemplateIntoString(indexTemplate, model);

        SearchIndex index = SearchIndex.fromJson(DefaultJsonReader.fromString(indexJson, new JsonOptions()));

        return AzureAiSearchEmbeddingStore.builder()
                .apiKey(envSearch.getApiKey())
                .endpoint(envSearch.getEndpoint())
                .createOrUpdateIndex(true)
                .index(index)
                .build();
    }
}
```
- Use it in a EmbeddingStoreIngestor : 
```
        EmbeddingStoreIngestor.builder()
                .documentSplitter(documentSplitter)
                .embeddingModel(embeddingModel)
                .embeddingStore(embeddingsStoreProvider.create(searchIndexName))
                .build();
```

- Make an ingestion, this error happens 
```
2024-06-07T17:44:29.174+02:00 DEBUG 112455 --- [ai-injector-api] [           main] d.l.s.embedding.EmbeddingStoreIngestor   : Starting to store 1 text segments into the embedding store
2024-06-07T17:44:29.298+02:00 ERROR 112455 --- [ai-injector-api] [           main] c.azure.search.documents.SearchClient    : Status code 404, "{"error":{"code":"","message":"The index 'vectorsearch' for service 'poc-rag-search-01' was not found."}}"

com.azure.search.documents.implementation.models.ErrorResponseException: Status code 404, "{"error":{"code":"","message":"The index 'vectorsearch' for service 'poc-rag-search-01' was not found."}}"
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[na:na]
	at com.azure.core.implementation.MethodHandleReflectiveInvoker.invokeWithArguments(MethodHandleReflectiveInvoker.java:39) ~[azure-core-1.49.0.jar:1.49.0]
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:53) ~[azure-core-1.49.0.jar:1.49.0]
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:408) ~[azure-core-1.49.0.jar:1.49.0]
	at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:133) ~[azure-core-1.49.0.jar:1.49.0]
	at com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:210) ~[azure-core-1.49.0.jar:1.49.0]
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:86) ~[azure-core-1.49.0.jar:1.49.0]
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:125) ~[azure-core-1.49.0.jar:1.49.0]
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:97) ~[azure-core-1.49.0.jar:1.49.0]
	at jdk.proxy2/jdk.proxy2.$Proxy115.indexSync(Unknown Source) ~[na:na]
	at com.azure.search.documents.implementation.DocumentsImpl.indexWithResponse(DocumentsImpl.java:769) ~[azure-search-documents-11.7.0-beta.3.jar:11.7.0-beta.3]
	at com.azure.search.documents.implementation.util.Utility.lambda$indexDocumentsWithResponse$1(Utility.java:170) ~[azure-search-documents-11.7.0-beta.3.jar:11.7.0-beta.3]
	at com.azure.search.documents.implementation.util.Utility.executeRestCallWithExceptionHandling(Utility.java:199) ~[azure-search-documents-11.7.0-beta.3.jar:11.7.0-beta.3]
	at com.azure.search.documents.implementation.util.Utility.indexDocumentsWithResponse(Utility.java:168) ~[azure-search-documents-11.7.0-beta.3.jar:11.7.0-beta.3]
	at com.azure.search.documents.SearchClient.indexDocumentsWithResponse(SearchClient.java:769) ~[azure-search-documents-11.7.0-beta.3.jar:11.7.0-beta.3]
	at com.azure.search.documents.SearchClient.uploadDocumentsWithResponse(SearchClient.java:422) ~[azure-search-documents-11.7.0-beta.3.jar:11.7.0-beta.3]
	at com.azure.search.documents.SearchClient.uploadDocuments(SearchClient.java:382) ~[azure-search-documents-11.7.0-beta.3.jar:11.7.0-beta.3]
	at dev.langchain4j.store.embedding.azure.search.AbstractAzureAiSearchEmbeddingStore.addAllInternal(AbstractAzureAiSearchEmbeddingStore.java:338) ~[langchain4j-azure-ai-search-0.31.0.jar:na]
	at dev.langchain4j.store.embedding.azure.search.AbstractAzureAiSearchEmbeddingStore.addAll(AbstractAzureAiSearchEmbeddingStore.java:250) ~[langchain4j-azure-ai-search-0.31.0.jar:na]
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:198) ~[langchain4j-core-0.31.0.jar:na]
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:150) ~[langchain4j-core-0.31.0.jar:na]

```

My understanding is that there is a mistake in the computation of the indexName. It's default name that is used, but it should be the name defined in the SearchIndex instance. Here the lines where the bug is : 
https://github.com/langchain4j/langchain4j/blob/39c9dfdbc60b2ff88f9848dd595d4ee6f3eae10b/langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java#L64-L86

I think the line 72 should be like : 
```
if (createOrUpdateIndex) {
    this.indexName = (index != null) ? index.getName() : DEFAULT_INDEX_NAME;
} else {
    this.indexName = (indexName != null) ? indexName : DEFAULT_INDEX_NAME;
}
```

### PR DESCRIPTION
**Pull request by jdubois**
Fix #1249

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Hi @jdubois thank you!
The logic here becomes complicated, I would add a few tests for this.

**Comment by jdubois** [comment]
Argh @langchain4j you were right! I added some tests and I believe I found a bug in the algorithm! @fb33 could you check this new code?

File: langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java [hunk 1]
```diff
@@ -68,8 +68,15 @@ protected void initialize(String endpoint, AzureKeyCredential keyCredential, Tok
             // if the indexName is provided, it will be used when creating the default index
             throw new IllegalArgumentException("index and indexName cannot be both defined");
         }
+        if (createOrUpdateIndex && index != null) {
```
Comment (fb33) [inline langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java:71]: Is it really what you want ?
I though it should be `(createOrUpdateIndex && index == null)`, because how do you create or update an index programmaticaly without the description of the index ?

File: langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java [hunk 2]
```diff
@@ -68,8 +68,15 @@ protected void initialize(String endpoint, AzureKeyCredential keyCredential, Tok
...
+            throw new IllegalArgumentException("createOrUpdateIndex is true: if the index is created or updated, then the index cannot also be provided");
+        }
         this.createOrUpdateIndex = createOrUpdateIndex;
-        this.indexName = getOrDefault(indexName, DEFAULT_INDEX_NAME);
+        if (createOrUpdateIndex) {
+            this.indexName = getOrDefault(indexName, DEFAULT_INDEX_NAME);
```
Comment (fb33) [inline langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java]: following my previous comment, I think it should be 
```
        if (createOrUpdateIndex) {
            this.indexName = index.getName();
        } else {
            this.indexName = getOrDefault(indexName, DEFAULT_INDEX_NAME);
        }
```

**Comment by jdubois** [comment]
@fb33 thanks for your review! I totally changed the code, and modify the code - I believe it's closer to what you suggested

**Review by fb33 — APPROVED** [review]
It looks fine ! :+1: 
Thanks

**Review by ghost — APPROVED** [review]
@jdubois thank you!
