### PR TITLE
fix: Avoid exception in HierarchicalDocumentSplitter when estimating size of blank strings

### LINKED ISSUE #4437: [BUG] Incomplete implementation of estimateSize method in HierarchicalDocumentSplitter leads to exception "text cannot be null or blank" when tokenCountEstimator is not null.
**Describe the bug**
Incomplete implementation of estimateSize method in HierarchicalDocumentSplitter class leads to exception "text cannot be null or blank" when tokenCountEstimator is not null and parameter of estimateSize method is a whitespace/blank string.

This method is being used to estimate the size of a given text. At some scenarios, this method is being passed a joinSeperator to get its length. When tokenCountEstimator is not null, this method directly proceeds to estimate the number of tokens in the string even for a whitespace string which is leading to a "text cannot be null or blank" exception.

**Log and Stack trace**
Caused by: java.lang.IllegalArgumentException: text cannot be null or blank
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:23) ~[langchain4j-core-1.10.0.jar:na]
	at dev.langchain4j.internal.ValidationUtils.ensureNotBlank(ValidationUtils.java:169) ~[langchain4j-core-1.10.0.jar:na]
	at dev.langchain4j.internal.ValidationUtils.ensureNotBlank(ValidationUtils.java:156) ~[langchain4j-core-1.10.0.jar:na]
	at dev.langchain4j.data.message.TextContent.<init>(TextContent.java:21) ~[langchain4j-core-1.10.0.jar:na]
	at dev.langchain4j.data.message.TextContent.from(TextContent.java:63) ~[langchain4j-core-1.10.0.jar:na]
	at dev.langchain4j.data.message.UserMessage.<init>(UserMessage.java:59) ~[langchain4j-core-1.10.0.jar:na]
	at dev.langchain4j.data.message.UserMessage.from(UserMessage.java:268) ~[langchain4j-core-1.10.0.jar:na]
	at dev.langchain4j.model.googleai.GoogleAiGeminiTokenCountEstimator.estimateTokenCountInText(GoogleAiGeminiTokenCountEstimator.java:47) ~[langchain4j-google-ai-gemini-1.10.0.jar:na]
	at dev.langchain4j.data.document.splitter.HierarchicalDocumentSplitter.estimateSize(HierarchicalDocumentSplitter.java:227) ~[langchain4j-1.10.0.jar:na]
	at dev.langchain4j.data.document.splitter.SegmentBuilder.sizeOf(SegmentBuilder.java:81) ~[langchain4j-1.10.0.jar:na]
	at dev.langchain4j.data.document.splitter.SegmentBuilder.<init>(SegmentBuilder.java:34) ~[langchain4j-1.10.0.jar:na]
	at dev.langchain4j.data.document.splitter.HierarchicalDocumentSplitter.split(HierarchicalDocumentSplitter.java:125) ~[langchain4j-1.10.0.jar:na]
	at dev.langchain4j.data.document.DocumentSplitter.lambda$splitAll$0(DocumentSplitter.java:38) ~[langchain4j-core-1.10.0.jar:na]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[na:na]
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853) ~[na:na]
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at dev.langchain4j.data.document.DocumentSplitter.splitAll(DocumentSplitter.java:38) ~[langchain4j-core-1.10.0.jar:na]
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:187) ~[langchain4j-core-1.10.0.jar:na]
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:156) ~[langchain4j-core-1.10.0.jar:na]
	at dev.langchain4j.example.CustomerSupportAgentConfiguration.embeddingStore(CustomerSupportAgentConfiguration.java:71) ~[classes/:na]
	

**To Reproduce**
I came across this error when I am testing customer-support-agent-example present in langchain4j-examples repo.

**Expected behavior**
estimateSize should return the size of whitespace string when tokenCountCalculator is not null.

### PR DESCRIPTION
**Pull request by jujn**
## Issue

Closes #4437 

## General checklist

- [x] There are no breaking changes (API, behaviour)
- [X] I have added unit and/or integration tests for my change
- [X] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

File: langchain4j/src/main/java/dev/langchain4j/data/document/splitter/HierarchicalDocumentSplitter.java [hunk 1]
```diff
@@ -223,7 +221,14 @@ String overlapFrom(String segmentText) {
      * @return The estimated number of tokens.
      */
     int estimateSize(String text) {
+        if (text == null) {
```
Comment (Bram--) [inline langchain4j/src/main/java/dev/langchain4j/data/document/splitter/HierarchicalDocumentSplitter.java]: Please use https://github.com/Bram--/langchain4j/blob/71e8c1d14702993b40ced42f2f8c7b2d69f3ded0/langchain4j-core/src/main/java/dev/langchain4j/internal/Utils.java#L123 here instead, this would also allow you to drop L229-L231.

**Review by Bram-- — CHANGES_REQUESTED** [review]
Thanks for the PR! Looks good to me, minor nit.

OOC - did all formatting come from running Sonatype?

**Comment by jujn** [comment]
> Thanks for the PR! Looks good to me, minor nit.
> OOC - did all formatting come from running Sonatype?

Thanks for the review! I've updated the code to use Utils.isNullOrBlank. As for the other code style changes, I'm not quite sure. I used the 'mvn spotless:apply' to format the code.

**Review by Bram-- — APPROVED** [review]
Looks good, thanks! 😄
