### PR TITLE
Exceptions during AiServiceEvents are eaten

### LINKED ISSUE #4499: [BUG] Exceptions during AiServiceEvents are eaten
In `DefaultAiServiceListenerRegistrar`, when a listener is fired, if that listener errors with an exception, the exception is logged but not re-thrown. This is a bug.

Anything downstream should be able to catch any exceptions thrown by the event listener.

**NOTE:** The fix will be backwards-compatible from a compilation standpoint, but will introduce a difference in functionality.

### PR DESCRIPTION
**Pull request by edeandrea**
Add support for exception handling configuration in `AiServiceListenerRegistrar`, enabling optional propagation of errors during event firing

Fixes #4499

## Issue

Closes #

## General checklist

- [X] There are no breaking changes (API, behaviour)
- [X] I have added unit and/or integration tests for my change
- [X] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [X] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

### CODE REVIEW

**Comment by edeandrea** [comment]
There's no breaking behavioral change here like I thought there might be. Whether exceptions are thrown or eaten can be configured on a per-registrar basis, which ends up as a per ai-service basis.

File: langchain4j-core/src/main/java/dev/langchain4j/observability/api/DefaultAiServiceListenerRegistrar.java [hunk 1]
```diff
@@ -24,6 +25,9 @@ public class DefaultAiServiceListenerRegistrar implements AiServiceListenerRegis
     private final Map<Class<? extends AiServiceEvent>, EventListeners<? extends AiServiceEvent>> listeners =
             new ConcurrentHashMap<>();
 
+    // Defaults to false to preserve backwards compatibility
+    private final AtomicBoolean shouldThrowExceptionOnEventError = new AtomicBoolean(false);
```
Comment (mariofusco) [inline langchain4j-core/src/main/java/dev/langchain4j/observability/api/DefaultAiServiceListenerRegistrar.java:29]: I'm not understanding why you're using an `AtomicBoolean` here. Can you please explain?

File: langchain4j-core/src/main/java/dev/langchain4j/observability/api/AiServiceListenerRegistrar.java [hunk 2]
```diff
@@ -83,17 +83,49 @@ default void unregister(Iterable<? extends AiServiceListener<?>> listeners) {
...
+     * Configures whether exceptions should be thrown when an error occurs during event processing.
+     * If set to {@code true}, any error that occurs while processing an event will result in an exception
+     * propagating to the caller. If set to {@code false}, errors will be silently handled or logged
+     * without interrupting the normal execution flow.
+     *
+     * @param shouldThrowExceptionOnEventError Indicates whether to throw exceptions on event errors.
+     *                                         If {@code true}, exceptions will be thrown; otherwise, errors
+     *                                         will be handled silently.
+     */
+    void shouldThrowExceptionOnEventError(boolean shouldThrowExceptionOnEventError);
```
Comment (dliubarskyi) [inline langchain4j-core/src/main/java/dev/langchain4j/observability/api/AiServiceListenerRegistrar.java:96]: Please mention default value in the javadoc

File: langchain4j-core/src/main/java/dev/langchain4j/observability/api/DefaultAiServiceListenerRegistrar.java (hunk 1 above)
Comment (edeandrea) [reply langchain4j-core/src/main/java/dev/langchain4j/observability/api/DefaultAiServiceListenerRegistrar.java:29]: Because multiple threads could possible be registering listeners and/or changing this value.

File: langchain4j-core/src/main/java/dev/langchain4j/observability/api/AiServiceListenerRegistrar.java (hunk 2 above)
Comment (edeandrea) [reply langchain4j-core/src/main/java/dev/langchain4j/observability/api/AiServiceListenerRegistrar.java:96]: Done

**Comment by edeandrea** [comment]
I'm not sure why the spotless check is failing. I ran spotless on the `langchain4j-core` module (the only one I made changes in) locally and it doesn't find anything that needs to be changed
.

**Review by mariofusco — APPROVED** [review]
