### PR TITLE
Log the HTTP request/response using VertexAiAnthropicChatModel

### LINKED ISSUE #4741: [FEATURE] Log the HTTP request/response using VertexAiAnthropicChatModel
# New feature

The `VertexAiAnthropicChatModel` when we request to log the Request or Response logs the following objects: 
- dev.langchain4j.model.vertexai.anthropic.internal.api.AnthropicRequest
- dev.langchain4j.model.vertexai.anthropic.internal.api.AnthropicResponse
but not at all the HTTP request/response (with headers, body).
Logging the objects are not really helpful for the users as they cannot see the endpoint generated, body, etc

I created a simple jbang example able to showcase what it happens
```
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.slf4j:slf4j-simple:2.0.17
//DEPS dev.langchain4j:langchain4j:1.12.2
//DEPS dev.langchain4j:langchain4j-anthropic:1.12.2
//DEPS dev.langchain4j:langchain4j-vertex-ai-anthropic:1.12.2-beta22
//RUNTIME_OPTIONS -Dorg.slf4j.simpleLogger.defaultLogLevel=info -Dorg.slf4j.simpleLogger.log.dev.langchain4j=debug

import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.model.vertexai.anthropic.VertexAiAnthropicChatModel;

public class VertexAIAnthropicChat {

    private static final String PROJECT_ID = "itpc-gcp-cp-pe-eng-claude";
    private static final String MODEL_NAME = "claude-opus-4-6";
    private static final String LOCATION = "europe-west1";

    public static void main(String[] args) {
        System.out.println("Starting AI chat ...");
        ChatModel model = VertexAiAnthropicChatModel.builder()
                .project(PROJECT_ID)
                .location(LOCATION)
                .modelName(MODEL_NAME)
                .maxTokens(1000)
                .logRequests(true)
                .logResponses(true)
                .build();

        System.out.println(model.chat("Hi Claude"));
    }
}
```
In a terminal
```
❯ jbang run -x ./ai/src/main/java/VertexAIAnthropicChat.java
[jbang] Building jar for VertexAIAnthropicChat.java...
Starting AI chat ...
[main] DEBUG dev.langchain4j.model.vertexai.anthropic.VertexAiAnthropicChatModel - Using model name: claude-opus-4-6 (from parameters: null, default: claude-opus-4-6)
[main] DEBUG dev.langchain4j.model.vertexai.anthropic.VertexAiAnthropicChatModel - Anthropic request: dev.langchain4j.model.vertexai.anthropic.internal.api.AnthropicRequest@2e77b8cf
[main] DEBUG dev.langchain4j.model.vertexai.anthropic.VertexAiAnthropicChatModel - Anthropic response: dev.langchain4j.model.vertexai.anthropic.internal.api.AnthropicResponse@27068a50
```

Example of content of the `AnthropicRequest` object:
```
endpoint: "projects/itpc-gcp-cp-pe-eng-claude/locations/europe-west1/publishers/anthropic/models/claude-opus-4-6"
http_body {
  content_type: "application/json"
  data: "{\"max_tokens\":1000,\"messages\":[{\"role\":\"user\",\"content\":[{\"type\":\"text\",\"text\":\"Hi Claude\"}]}],\"anthropic_version\":\"vertex-2023-10-16\"}"
}
```

For your information, when this code is executed, we don't log any messages
```java

public ChatResponse doChat(ChatRequest chatRequest) {
...
AnthropicResponse anthropicResponse = this.client.generateContent(anthropicRequest, requestModelName);
...
private AnthropicResponse generateContentWithRetry(AnthropicRequest request, String modelName, int attempt) throws IOException {
        if (request == null) {
            throw new IllegalArgumentException("request cannot be null");
        } else {
            try {
                Map<String, Object> requestMap = this.buildRequestMap(request);
                String requestJson = this.objectMapper.writeValueAsString(requestMap);
                RawPredictRequest rawPredictRequest = this.buildRawPredictRequest(requestJson, modelName);
                HttpBody response = this.predictionServiceClient.rawPredict(rawPredictRequest);
                String responseJson = response.getData().toStringUtf8();
                return (AnthropicResponse)this.objectMapper.readValue(responseJson, AnthropicResponse.class);
            } catch (UnavailableException e) {
                return this.handleUnavailableException(e, request, modelName, attempt);
            } catch (Exception e) {
                throw new IOException("Failed to generate content using Vertex AI rawPredict", e);
            }
        }
    }
```

### PR DESCRIPTION
**Pull request by DakshRJain737**
## Issue

Closes #4741 

## Change

Log the HTTP request/response using VertexAiAnthropicChatModel
Rather than logging Object reference, the details of the HTTP request and response are logged.

## General checklist

- [X] There are no breaking changes (API, behaviour)
- [] I have added unit and/or integration tests for my change
- [ ] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [X] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by dliubarskyi** [comment]
@cmoulliard could you please review? 🙏

**Review by cmoulliard — COMMENTED** [review]
Is it possible to log additional data as the `baseUrl` for the Request and for each message, the role and content like the tools requested ?

**Comment by DakshRJain737** [comment]
> Is it possible to log additional data as the `baseUrl` for the Request and for each message, the role and content like the tools requested ?

info related to tools and tools choice is logged along with the request itself.
Base url done

Done

File: langchain4j-vertex-ai-anthropic/src/main/java/dev/langchain4j/model/vertexai/anthropic/internal/client/VertexAiAnthropicClient.java [hunk 1]
```diff
@@ -159,6 +164,7 @@ private AnthropicResponse generateContentWithRetry(AnthropicRequest request, Str
 
             RawPredictRequest rawPredictRequest = buildRawPredictRequest(requestJson, modelName);
             HttpBody response = predictionServiceClient.rawPredict(rawPredictRequest);
+            logger.debug(predictionServiceClient.getSettings().getEndpoint());
```
Comment (cmoulliard) [inline langchain4j-vertex-ai-anthropic/src/main/java/dev/langchain4j/model/vertexai/anthropic/internal/client/VertexAiAnthropicClient.java]: This line will log in debug mode the resolved endpoint. This is great but that will be perhaps a bit confusing for the end users as they expect, if they enable on the builder, to log the response or request to see such an information independently of the logging level.

That came my additional point which concerns the logging level; should we see such information using `log.info` or `log.debug`. The answer really depend also on langchain4j convention ?

@DakshRJain737

Comment (DakshRJain737) [reply langchain4j-vertex-ai-anthropic/src/main/java/dev/langchain4j/model/vertexai/anthropic/internal/client/VertexAiAnthropicClient.java]: Yes I missed that.
I have updated changes on logging baseUrl.
langchain4j uses `log.debug` everywhere.
Any changes to be made?

**Review by cmoulliard — APPROVED** [review]

**Comment by DakshRJain737** [comment]
@dliubarskyi I think good to merge.
