### PR TITLE
Azure CosmosDB No SQL: Fixing bugs

### LINKED ISSUE #3634: [BUG] NPE when using `AzureCosmosDBNoSqlEmbeddingStore`
**Describe the bug**

This [PR](https://github.com/langchain4j/langchain4j/pull/3463) has introduced at least two bugs in `AbstractAzureCosmosDBNoSqlEmbeddingStore` that lead to NPE:
1. `switch` should be over `this.searchQueryType` but it is over `searchQueryType`
```java
this.searchQueryType = getOrDefault(searchQueryType, DEFAULT_SEARCH_QUERY_TYPE);
switch (searchQueryType) {
            case VECTOR -> {
...
}
```

2. In the `search()` method, `this.indexingPolicy` is used but `this.indexingPolicy` is never initialized.

There is another change in the PR that could potentially be problematic. With this PR a `CosmosClient` is created inside the constructor, and so there is no need to pass an in instance of `CosmosClient` to the builder. The downside of this is that we cannot call the `close()` method on the instance of `CosmosClient` in order to release the resources.

**Log and Stack trace**

```Java
java.lang.NullPointerException: Cannot invoke "com.azure.cosmos.models.IndexingPolicy.getVectorIndexes()" because "this.indexingPolicy" is null
	at dev.langchain4j.store.embedding.azure.cosmos.nosql.AbstractAzureCosmosDBNoSqlEmbeddingStore.search(AbstractAzureCosmosDBNoSqlEmbeddingStore.java:413)
```

**To Reproduce**

Build an instance of `AzureCosmosDbNoSqlEmbeddingStore` and call the `search()` method on it.

**Expected behavior**

There should be no NPE.

**Please complete the following information:**
- LangChain4j version: 1.4.0
- LLM(s) used: -
- Java version: 21
- Spring Boot version (if applicable): -

**Additional context**

### PR DESCRIPTION
**Pull request by aayush3011**
## Issue
Fixes https://github.com/langchain4j/langchain4j/issues/3634 and some pending comments from the PR https://github.com/langchain4j/langchain4j/pull/3463

## General checklist
- [ ] There are no breaking changes (API, behaviour)
- [x] I have added unit and/or integration tests for my change
- [x] The tests cover both positive and negative cases
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)

### CODE REVIEW

**Comment by aayush3011** [comment]
@dliubarskyi please review once you have a chance.

File: langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/AzureCosmosDBNoSqlContentRetriever.java [hunk 1]
```diff
@@ -37,63 +37,48 @@ public class AzureCosmosDBNoSqlContentRetriever extends AbstractAzureCosmosDBNoS
     private final double minScore;
     private final Filter filter;
 
-    public AzureCosmosDBNoSqlContentRetriever(
```
Comment (dliubarskyi) [inline langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/AzureCosmosDBNoSqlContentRetriever.java:40]: Please consider making it `@Deprecated(forRemoval=true)` instead of removing completely and making a breaking change for users?

**Comment by dliubarskyi** [comment]
@aayush3011 please fill out the "General checklist".

FYI: I (and CI) cannot test your PR, so **_I fully rely on you running tests locally_**, please confirm that tests are green with your latest changes

**Comment by dliubarskyi** [comment]
@aayush3011 is your sumbs up reaction means that you confirm that this is tested and can be merged?

File: langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/AzureCosmosDBNoSqlContentRetriever.java (hunk 1 above)
Comment (aayush3011) [reply langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/AzureCosmosDBNoSqlContentRetriever.java:40]: Added the deprecated constructor back.

**Comment by aayush3011** [comment]
@dliubarskyi I have taken care of all the comments, and the PR is tested and everything is green.

**Review by dliubarskyi — APPROVED** [review]
@aayush3011 thank you!
