### PR TITLE
Retrive the AgenticScope of agents related events from the InvocationContext

### LINKED ISSUE #4795: [BUG] LangChain4jManaged.current() is null
**Title:**
`[Bug] NullPointerException when combining Listener and TokenStream in Agentic Workflow (Beta 22)`

**Describe the bug**
I am encountering a `java.lang.NullPointerException` when using the `langchain4j-agentic` module. The issue occurs specifically when I configure an Agent with both a `.listener()` and attempt to return the response via `TokenStream` (streaming).

It seems that `LangChain4jManaged.current()` returns `null` during the tool execution phase within the streaming callback, causing the agent to crash when trying to access the invocation context.

**Log and Stack trace**
```java
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "dev.langchain4j.invocation.LangChain4jManaged.current()" is null 
    at dev.langchain4j.agentic.agent.AgentInvocationHandler.lambda$registerInheritedParentListener$0(AgentInvocationHandler.java:145) 
    at dev.langchain4j.service.tool.ToolService.internalExecuteTool(ToolService.java:564) 
    at dev.langchain4j.service.tool.ToolService.executeTool(ToolService.java:542) 
    at dev.langchain4j.service.AiServiceStreamingResponseHandler.execute(AiServiceStreamingResponseHandler.java:442) 
    at dev.langchain4j.service.AiServiceStreamingResponseHandler.onCompleteResponse(AiServiceStreamingResponseHandler.java:329) 
    at dev.langchain4j.model.chat.StreamingChatModel$1.onCompleteResponse(StreamingChatModel.java:91) 
    at dev.langchain4j.internal.InternalStreamingChatResponseHandlerUtils.onCompleteResponse(InternalStreamingChatResponseHandlerUtils.java:136) 
    at dev.langchain4j.model.openai.OpenAiStreamingChatModel.lambda$doChat$1(OpenAiStreamingChatModel.java:170) 
    ...
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) 
    ...
```

**To Reproduce**
1. Create a sequence or conditional agent using `AgenticServices`.
2. Attach a `.listener()` to the agent builder.
3. Invoke the agent and attempt to consume the result via `TokenStream` (streaming).
4. The error triggers when the agent attempts to execute a tool or manage the context during the stream.

**Code snippet to reproduce:**
```java
@Bean
public ChatAgent chatAgent(PolicyAgent policyAgent, CommonAgent commonAgent, GenerateSearchAgent generateSearchAgent, ArticleSearchAgent articleSearchAgent, ResultsProcessAgent resultsProcessAgent) {

    UntypedAgent articleAgent = AgenticServices.sequenceBuilder()
            .subAgents(generateSearchAgent, articleSearchAgent)
            .outputKey("result")
            .build();

    UntypedAgent routerAgent = AgenticServices.conditionalBuilder()
            .subAgents(agenticScope -> agenticScope.readState("policy", 0) == 0, commonAgent)
            .subAgents(agenticScope -> agenticScope.readState("policy", 0) == 1, articleAgent)
            .outputKey("result")
            .build();

    // The issue happens here: combining .listener() with the streaming execution of this agent
    return AgenticServices.sequenceBuilder(ChatAgent.class)
            .subAgents(policyAgent, routerAgent)
            .listener(myAgentListener) 
            .build();
}
```

**Expected behavior**
The agent should execute the workflow, trigger the listener events, and stream the tokens back to the client without throwing a NullPointerException.

**Please complete the following information:**
- **LangChain4j version:** `1.12.2` (specifically `langchain4j-agentic-1.12.2-beta22`)
- **LLM(s) used:** DeepSeek (via OpenAI compatible interface)
- **Java version:** 21
- **Spring Boot version:** 2.7.18

**Additional context**
The stack trace suggests that the `AgentInvocationHandler` is trying to register an inherited parent listener, but fails because the `LangChain4jManaged` context is missing in the thread executing the streaming response (`ForkJoinPool` thread).

### PR DESCRIPTION
**Pull request by mariofusco**
## Issue

Closes #4795

## Change

The main improvement introduced by this pull request is adding the `InvocationContext` to both the `BeforeToolExecution` and `ToolExecution` classes. In this way the agentic framework can retrieve the current `AgenticScope` from there instead of relying on the `ThreadLocal`-based `LangChain4jManaged` that doesn't work in case of asynchronous executions. In the same way the agentic framework retrieves the `AgenticScope` from the `AiServiceResponseReceivedEvent` that already contained the `InvocationContext` even before.

Not strictly related to this it also creates an ephemeral `AgenticScope` in the degenerate case when a single agent is invoked in isolation, outside any agentic system, also emetting a warning when this happens.

## General checklist

- [X] There are no breaking changes (API, behaviour)
- [X] I have added unit and/or integration tests for my change
- [X] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

File: langchain4j/src/main/java/dev/langchain4j/service/tool/BeforeToolExecution.java [hunk 1]
```diff
@@ -13,9 +14,11 @@
 public class BeforeToolExecution {
 
     private final ToolExecutionRequest request;
+    private final InvocationContext invocationContext;
 
     private BeforeToolExecution(Builder builder) {
         this.request = ensureNotNull(builder.request, "request");
+        this.invocationContext = ensureNotNull(builder.invocationContext, "invocationContext");
```
Comment (dliubarskyi) [inline langchain4j/src/main/java/dev/langchain4j/service/tool/BeforeToolExecution.java:21]: please check validations of `invocationContext` in all places in this PR, they are not consistent now

Comment (mariofusco) [reply langchain4j/src/main/java/dev/langchain4j/service/tool/BeforeToolExecution.java:21]: True, I guess that we want to enforce everywhere that it is not null, correct?

Comment (mariofusco) [reply langchain4j/src/main/java/dev/langchain4j/service/tool/BeforeToolExecution.java:21]: Done.

**Review by dliubarskyi — APPROVED** [review]
@mariofusco thank you!
