### PR TITLE
Fix: OpenAI, Azure OpenAI: throw ContentFilteredException in case of content filtered or refusal

### LINKED ISSUE #2137: [BUG] Exceptions due to Azure Content Filter
**Describe the bug**

We are building a RAG service with langchain4j and Azure Open AI and got some unexpected exceptions due to empty response content. We investigated the issue and found that the Azure Content Filter filtered the response (`finish_reason: content_filter`). It seems that langchain4j currently does not handle this case properly.

**Log and Stack trace**

The problem occured with normal and streaming chat models. Maybe embedding models are affected as well.

**AzureOpenAiStreamingChatModel:**
```
java.lang.IllegalArgumentException: response cannot be null
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:50) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:37) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.model.chat.listener.ChatModelResponseContext.<init>(ChatModelResponseContext.java:25) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.model.azure.AzureOpenAiStreamingChatModel.lambda$asyncCall$5(AzureOpenAiStreamingChatModel.java:385) ~[langchain4j-azure-open-ai-0.35.0.jar!/:?]
	at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxReplay$UnboundedReplayBuffer.replayNormal(FluxReplay.java:602) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxReplay$UnboundedReplayBuffer.replay(FluxReplay.java:709) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxReplay$ReplaySubscriber.onComplete(FluxReplay.java:1373) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onComplete(FluxConcatMapNoPrefetch.java:241) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.doComplete(FluxPublishOn.java:511) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.checkTerminated(FluxPublishOn.java:558) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:438) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:533) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.11.jar!/:3.6.11]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

**AzureOpenAiChatModel:**

```
java.lang.IllegalArgumentException: text cannot be null
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:50) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:37) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.data.message.AiMessage.<init>(AiMessage.java:30) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.data.message.AiMessage.from(AiMessage.java:116) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.data.message.AiMessage.aiMessage(AiMessage.java:157) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.model.azure.InternalAzureOpenAiHelper.aiMessageFrom(InternalAzureOpenAiHelper.java:274) ~[langchain4j-azure-open-ai-0.35.0.jar!/:?]
	at dev.langchain4j.model.azure.AzureOpenAiChatModel.generate(AzureOpenAiChatModel.java:292) ~[langchain4j-azure-open-ai-0.35.0.jar!/:?]
	at dev.langchain4j.model.azure.AzureOpenAiChatModel.generate(AzureOpenAiChatModel.java:237) ~[langchain4j-azure-open-ai-0.35.0.jar!/:?]
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:44) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:32) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.rag.query.transformer.CompressingQueryTransformer.transform(CompressingQueryTransformer.java:74) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.rag.DefaultRetrievalAugmentor.augment(DefaultRetrievalAugmentor.java:151) ~[langchain4j-core-0.35.0.jar!/:?]
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:136) ~[langchain4j-0.35.0.jar!/:?]
	at jdk.proxy2/jdk.proxy2.$Proxy171.chat(Unknown Source) ~[?:?]
	at com.ChatService.chat(ChatService.kt:48) ~[!/:1.0.0]
```

**A filtered response looks like this:**

```
{"az.sdk.message":"HTTP response","statusCode":200,"url":"https://<endpoint>.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2024-07-01-preview","durationMs":807,"content-length":854,"Date":"<date>","Content-Type":"application/json","x-ms-client-request-id":"<uuid>","redactedHeaders":"x-request-id,x-ms-region,x-envoy-upstream-service-time,apim-request-id,x-ratelimit-remaining-tokens,x-ratelimit-remaining-requests,Strict-Transport-Security,azureml-model-session,x-content-type-options,x-accel-buffering,x-ms-rai-invoked","content-length":854,"body":"{\"choices\":[{\"content_filter_results\":{\"hate\":{\"filtered\":false,\"severity\":\"safe\"},\"self_harm\":{\"filtered\":false,\"severity\":\"safe\"},\"sexual\":{\"filtered\":true,\"severity\":\"medium\"},\"violence\":{\"filtered\":false,\"severity\":\"safe\"}},\"finish_reason\":\"content_filter\",\"index\":0,\"logprobs\":null,\"message\":{\"role\":\"assistant\"}}],\"created\":<timestamp>,\"id\":\"chatcmpl-<id>\",\"model\":\"gpt-4o-mini\",\"object\":\"chat.completion\",\"prompt_filter_results\":[{\"prompt_index\":0,\"content_filter_results\":{\"hate\":{\"filtered\":false,\"severity\":\"safe\"},\"jailbreak\":{\"filtered\":false,\"detected\":false},\"self_harm\":{\"filtered\":false,\"severity\":\"safe\"},\"sexual\":{\"filtered\":false,\"severity\":\"safe\"},\"violence\":{\"filtered\":false,\"severity\":\"safe\"}}}],\"system_fingerprint\":\"fp_<id>\",\"usage\":{\"completion_tokens\":9,\"prompt_tokens\":1079,\"total_tokens\":1088}}\n"}
```

**To Reproduce**

I'm unable to provide an request for reproduction, as it contains customer content.
We believe that this is a false-positive from the Azure Content Filter, since the request does not contain any sexual content.

**Expected behavior**

We do not expect those exceptions to be thrown, we would like to have proper error handling for responses filtered by Azure Content Filter.

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: GPT-4o-mini
- Java version: 21
- Spring Boot version (if applicable): 3.3.5

**Additional context**

### LINKED ISSUE #3138: [BUG] Can't parse OpenAI's response with string "refusal". Moderation error not thrown
**Describe the bug**
Sometimes, LLM answers with "refusal" being string:
```json
...
"choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": null,
        "refusal": "I'm sorry, but I can't assist with that request.",
        "annotations": []
      },
```
`dev.langchain4j.model.openai.internal.chat.AssistantMessage.refusal` has a boolean type, so it's deserialization fails:

**Log and Stack trace**

```
 jakarta.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Boolean` from String "I'm sorry, but I can't assist with that request.": only "true" or "false" recognized
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 12, column: 20] (through reference chain: dev.langchain4j.model.openai.internal.chat.ChatCompletionResponse$Builder["choices"]->java.util.ArrayList[0]->dev.langchain4j.model.openai.internal.chat.ChatCompletionChoice$Builder["message"]->dev.langchain4j.model.openai.internal.chat.AssistantMessage$Builder["refusal"])
```

**To Reproduce**

1. Clone https://github.com/kpavlov/quarkus-assistant-demo/tree/c58ff6457e758b0e8f429cfd47d4abbee2aec28d
2. Remove [this system prompt hack](https://github.com/kpavlov/quarkus-assistant-demo/blob/c58ff6457e758b0e8f429cfd47d4abbee2aec28d/src/main/resources/prompts/assistant-system-prompt.md?plain=1#L40-L41)
3. Provide opeapi key in `.env` and and run `mvn quarkus:dev'
4. Ask for instructions to build a bomb to harm people

**Expected behavior**

Expected [AiService](https://github.com/kpavlov/quarkus-assistant-demo/blob/c58ff6457e758b0e8f429cfd47d4abbee2aec28d/src/main/kotlin/com/example/chatbot/Assistant.kt#L36) to throw ModerationException.

**Actual behavior**

jakarta.ws.rs.ProcessingException:

**Please complete the following information:**
- LangChain4j version: 1.0.1
- LLM(s) used: OpenAi 
- Java version: 24
- Quarkus-Langchain4j: 1.0.0.CR2

**Additional context**

https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/Quarkus.20LangChain4J.20Moderation/with/521519320

### LINKED ISSUE #3260: [BUG] Azure OpenAI: IllegalArgumentException is thrown when content has been filtered
**Describe the bug**
1. Configure custom content filter (e.g. "doFilterThis") in azure portal and assign it to your llm deployment
2. Send request to llm with "doFilterThis" 

**Log and Stack trace**
Caused by: java.lang.IllegalArgumentException: text cannot be null
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:23) ~[langchain4j-core-1.1.0.jar:?]
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:54) ~[langchain4j-core-1.1.0.jar:?]
	at dev.langchain4j.internal.ValidationUtils.ensureNotNull(ValidationUtils.java:41) ~[langchain4j-core-1.1.0.jar:?]
	at dev.langchain4j.data.message.AiMessage.<init>(AiMessage.java:32) ~[langchain4j-core-1.1.0.jar:?]
	at dev.langchain4j.data.message.AiMessage.from(AiMessage.java:142) ~[langchain4j-core-1.1.0.jar:?]
	at dev.langchain4j.data.message.AiMessage.aiMessage(AiMessage.java:183) ~[langchain4j-core-1.1.0.jar:?]
	at dev.langchain4j.model.azure.InternalAzureOpenAiHelper.aiMessageFrom(InternalAzureOpenAiHelper.java:368) ~[langchain4j-azure-open-ai-1.1.0-rc1.jar:?]
	at dev.langchain4j.model.azure.AzureOpenAiChatModel.doChat(AzureOpenAiChatModel.java:204) ~[langchain4j-azure-open-ai-1.1.0-rc1.jar:?]
	at dev.langchain4j.model.chat.ChatModel.chat(ChatModel.java:46) ~[langchain4j-core-1.1.0.jar:?]

**Expected behavior**
- Throw a ContentFilteredException

**Please complete the following information:**
- LangChain4j version: 1.1.0
- LLM(s) used: chatGPT 4o / 4o-mini azure
- Java version: 17

**Additional context**
This does not refer to the IllegalArgumentException but the OpenAiStreamingChatModel produces a httpResponseException without finish reason. It just has "code": "content_filter" in the message text. This is hard to handle.

### PR DESCRIPTION
**Pull request by dliubarskyi**
## Issue
Fixes https://github.com/langchain4j/langchain4j/issues/2137
Fixes https://github.com/langchain4j/langchain4j/issues/3138
Fixes https://github.com/langchain4j/langchain4j/issues/3260
Closes https://github.com/langchain4j/langchain4j/pull/3286

### OpenAI
When response contains `refusal` field, throw `ContentFilteredException` with the contents of  the `refusal` field.

### Azure OpenAI
Convert Azure's `HttpResponseException` containing filter error into a more specific `ContentFilteredException`.
When Azure returns finish reason `CONTENT_FILTERED`, throw `ContentFilteredException`.

## General checklist
- [X] There are no breaking changes
- [X] I have added unit and/or integration tests for my change
- [X] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

File: langchain4j-core/src/main/java/dev/langchain4j/exception/ContentFilteredException.java [hunk 1]
```diff
@@ -0,0 +1,23 @@
+package dev.langchain4j.exception;
+
+/**
+ * Exception thrown when the LLM provider refuses to process a request due to content filtering
+ * or violation of usage policies.
+ * <p>
+ * This typically indicates that the input was flagged as inappropriate, unsafe, or against
+ * the provider’s content guidelines.
+ */
+public class ContentFilteredException extends InvalidRequestException {
```
Comment (kpavlov) [inline langchain4j-core/src/main/java/dev/langchain4j/exception/ContentFilteredException.java:12]: I wouldn't extend it from `InvalidRequestException`, because request is, formally, valid. Extending from `NonRetriableException` looks legit for me.

Let's also introduce a dedicated field in the `ContentFilteredException` to store the content, e.g. `reason`. Otherwise, the raw LLM response would end up in logs. Exception message should be more neutral, like "LLM has refused to process the request".

File: langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/chat/AssistantMessage.java [hunk 2]
```diff
@@ -31,7 +31,7 @@ public final class AssistantMessage implements Message {
     @JsonProperty
     private final List<ToolCall> toolCalls;
     @JsonProperty
-    private final Boolean refusal;
+    private final String refusal;
```
Comment (kpavlov) [inline langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/chat/AssistantMessage.java:34]: :+1: That helps to fix #3138, but mapping ContentFilteredException to ModerationException is probably required. Need a unit test to prove that

File: langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/OpenAiUtils.java [hunk 3]
```diff
@@ -312,6 +314,11 @@ public static AiMessage aiMessageFrom(ChatCompletionResponse response) {
                     : AiMessage.from(text, singletonList(toolExecutionRequest));
         }
 
+        String refusal = assistantMessage.refusal();
+        if (isNullOrBlank(text) && isNotNullOrBlank(refusal)) {
```
Comment (kpavlov) [inline langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/OpenAiUtils.java]: I would remove `isNullOrBlank(text)` condition. `isNotNullOrBlank(refusal)` is enough

File: langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelErrorsTest.java [hunk 4]
```diff
@@ -94,4 +96,50 @@ void should_handle_timeout(int millis) {
...
+
+    @Test
+    void should_handle_refusal() {
+
+        // given
+        final var userMessage = "does not matter";
+        MOCK.completion(req -> req.userMessageContains(userMessage)).respondsError(res -> {
+            res.setHttpStatus(HttpStatusCode.Companion.fromValue(200));
+            // copied from https://platform.openai.com/docs/guides/structured-outputs/refusals?api-mode=chat#refusals
+            res.setBody("""
```
Comment (kpavlov) [inline langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelErrorsTest.java:112]: nit: Add `//language=json` to make IDEA highlight json text as json

File: langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelErrorsTest.java [hunk 5]
```diff
@@ -94,4 +96,50 @@ void should_handle_timeout(int millis) {
...
+                      },
+                      "system_fingerprint": "fp_3407719c7f"
+                    }
+                    """);
+        });
+
+        // when-then
+        assertThatThrownBy(() -> model.chat(userMessage))
+                .isExactlyInstanceOf(dev.langchain4j.exception.ContentFilteredException.class)
+                .hasMessage("I'm sorry, I cannot assist with that request.");
```
Comment (kpavlov) [inline langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelErrorsTest.java:147]: Let's introduce a dedicated field in the `ContentFilteredException` to store the content, e.g. `reason`. Otherwise, the raw LLM response would end up in logs. Exception message should be more neutral, like "LLM has refused to process the request".

File: langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/OpenAiUtils.java (hunk 3 above)
Comment (kpavlov) [inline langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/OpenAiUtils.java]:
```suggestion
        if (isNotNullOrBlank(refusal)) {
```

I would remove `isNullOrBlank(text)` condition. The `isNotNullOrBlank(refusal)` seems to be enough

**Review by kpavlov — APPROVED** [review]
Thank you, @dliubarskyi !
I think there is one thing missing: to map `ContentFilteredException` to `ModerationException` in AiServices, but this can be done in a separate PR.
Not exposing "content" from LLM response as exception message can be done as a follow-up PR as well.

**Review by kpavlov — DISMISSED** [review]
Thank you, @dliubarskyi !
I think there is one thing missing: to map `ContentFilteredException` to `ModerationException` in AiServices, but this can be done in a separate PR.
Not exposing "content" from LLM response as exception message can be done as a follow-up PR as well.

**Comment by kpavlov** [comment]
run `make format` to make spotless happy

**Comment by dliubarskyi** [comment]
@kpavlov thanks for the review!

> I think there is one thing missing: to map ContentFilteredException to ModerationException in AiServices, but this can be done in a separate PR.

Not sure about that, `ModerationException` has a different use case - when moderation is done actively by a `ModerationModel`.

File: langchain4j-core/src/main/java/dev/langchain4j/exception/ContentFilteredException.java (hunk 1 above)
Comment (dliubarskyi) [reply langchain4j-core/src/main/java/dev/langchain4j/exception/ContentFilteredException.java:12]: > I wouldn't extend it from InvalidRequestException, because request is, formally, valid. Extending from NonRetriableException looks legit for me.

The request is not valid as it's content is not valid (according to the filter), so it cannot be processed by the API, I see no issue here. It is also a backwards-compatible change as there might be users that already catch `InvalidRequestException` specifically for this situation

> Let's also introduce a dedicated field in the ContentFilteredException to store the content, e.g. reason. Otherwise, the raw LLM response would end up in logs.

Not sure I understand how adding a field will affect logs in any way?

File: langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/chat/AssistantMessage.java (hunk 2 above)
Comment (dliubarskyi) [reply langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/chat/AssistantMessage.java:34]: As explained in other comment, `ModerationException` is for other use case. `ContentFilteredException` is thrown when `refusal` is present

File: langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelErrorsTest.java (hunk 5 above)
Comment (dliubarskyi) [reply langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelErrorsTest.java:147]: > Otherwise, the raw LLM response would end up in logs

In the case of OpenAI, there will be no raw content in logs, only "I'm sorry, I cannot assist with that request." message.

In case of Azure OpenAI, they provide this:
> Status code 400, "{"error":{"message":"The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766","type":null,"param":"prompt","code":"content_filter","status":400,"innererror":{"code":"ResponsibleAIPolicyViolation","content_filter_result":{"hate":{"filtered":false,"severity":"safe"},"jailbreak":{"filtered":false,"detected":false},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":true,"severity":"medium"}}}}}"

What exactly do you want to put into that dedicated field?

File: langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/OpenAiUtils.java (hunk 3 above)
Comment (dliubarskyi) [reply langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/OpenAiUtils.java]: I was not sure about it, so added an extra check, but you are probably right that it is an overkill

**Comment by kpavlov** [comment]
> Not sure about that, `ModerationException` has a different use case - when moderation is done actively by a `ModerationModel`.

If ModerationModel runs **in parallel** with ChatModel as it is currently implemented in the [DefaultAiServices](https://github.com/langchain4j/langchain4j/blob/7d413d24c226fba33c339d7b7d1877566536dfb6/langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java#L207), then the ChatModel will throw the ContentFilteredException. 
From the AiService's user - it's the same.
Should the moderation become an input guardrail? Even in this case, the ChatModel might throw ContentFilteredException by it's own reasons (maybe moderation did not catch something) and it still needs to be handled.
I'd prefer to have a separate PR for AiServices, but I am sure we shouldn't close #3138 without a proper test.

**Comment by dliubarskyi** [comment]
@kpavlov 

> If ModerationModel runs in parallel with ChatModel as it is currently implemented in the [DefaultAiServices](https://github.com/langchain4j/langchain4j/blob/7d413d24c226fba33c339d7b7d1877566536dfb6/langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java#L207), then the ChatModel will throw the ContentFilteredException.
> From the AiService's user - it's the same.

If moderation fails due to the `ModerationModel`, then `ModerationException` will be thrown.
If `ChatModel` refuses to process the input, then `ContentFilteredException` will be thrown.
I am not entirely sure we should mix these 2 cases. 

> Should the moderation become an input guardrail?

Good question, probably yes, but I am not sure this feature is used much to invest in rewriting it TBH.

> Even in this case, the ChatModel might throw ContentFilteredException by it's own reasons (maybe moderation did not catch something) and it still needs to be handled.

How do you expect it to be handled? User should handle the exception when calling AI service in my understanding.

> I'd prefer to have a separate PR for AiServices, but I am sure we shouldn't close https://github.com/langchain4j/langchain4j/issues/3138 without a proper test.

But there is a test for https://github.com/langchain4j/langchain4j/issues/3138 [here](https://github.com/langchain4j/langchain4j/pull/3294/files#diff-8493063bfe46461de30d6a7ee43eaf14b4ae9f0c13a32466449f83e0b5af8085R101)

**Comment by dliubarskyi** [comment]
@kpavlov BTW, `ModerationException` is located in the `langchain4j` module and is used only for `@Moderate` feature of AI Services.
The newly introduced `ContentFilteredException` is located in the `langchain4j-core` module and is used by the low-level `ChatModel` API.

On the AI service level we can technically map `ContentFilteredException` into `ModerationException`, but in my understanding those are for 2 distinct situations, so I would not map.

**Comment by kpavlov** [comment]
> @kpavlov BTW, `ModerationException` is located in the `langchain4j` module and is used only for `@Moderate` feature of AI Services. The newly introduced `ContentFilteredException` is located in the `langchain4j-core` module and is used by the low-level `ChatModel` API.
> 
> On the AI service level we can technically map `ContentFilteredException` into `ModerationException`, but in my understanding those are for 2 distinct situations, so I would not map.

Yep, I noticed that the exceptions are defined on the different abstraction layers. Maybe adding ContentFilteredException as a cause of ModerationException would be a enough.

**Comment by kpavlov** [comment]
@dliubarskyi , please consider [this pr](https://github.com/langchain4j/langchain4j/pull/3310) since it updates the negative tests. Might be a conflict
