### PR TITLE
Replace properties() with addProperties in the JsonObjectSchema builder

### LINKED ISSUE #2419: [BUG] JsonObjectSchema.Builder: Properties Added via addStringProperty() Are Overwritten by properties() Method
**Describe the bug**
Properties added to JsonObjectSchema.Builder using `addStringProperty()`, `addNumberProperty()`, etc. are lost when `properties()` is subsequently called. This makes it impossible to combine direct property addition with nested properties, as the nested properties must be added via the properties map.

**Log and Stack trace**
No exception is thrown, but properties silently disappear. This can be demonstrated with the following test output:
```
Expected: Map containing "field1"
     but: was Map{nested=JsonObjectSchema{...}}
```

**To Reproduce**
```java
@Test
void demonstratePropertyLoss() {
    JsonSchema schema = JsonSchema.builder()
        .name("Example")
        .rootElement(JsonObjectSchema.builder()
            // This property will be lost
            .addStringProperty("field1", "First field")
            .properties(Map.of(
                "nested", JsonObjectSchema.builder()
                    .addStringProperty("subfield", "Nested field")
                    .build()
            ))
            .build())
        .build();

    JsonObjectSchema rootElement = (JsonObjectSchema) schema.rootElement();
    Map<String, JsonSchemaElement> properties = rootElement.properties();
    
    // field1 is not present in the final schema
    assert !properties.containsKey("field1");
    // only the nested property remains
    assert properties.containsKey("nested");
}
```

**Expected behavior**
Properties added via `addStringProperty()` and similar methods should be preserved when `properties()` is called. The final schema should contain both directly added properties and those provided via the properties map.

Expected properties map should contain:
```java
{
    "field1": JsonStringSchema{...},
    "nested": JsonObjectSchema{...}
}
```

**Please complete the following information:**
- LangChain4j version: 0.36.2
- LLM(s) used: OpenAI GPT-4
- Java version: 21
- Spring Boot version: 3.3.0

**Additional context**
This issue appears to be caused by the `properties()` method overwriting the internal properties map rather than merging with existing properties. The current workaround is to collect all properties in a mutable map first:

```java
Map<String, JsonSchemaElement> properties = new HashMap<>();

// Add direct property
properties.put("field1", JsonStringSchema.builder()
    .description("First field")
    .build());

// Add nested property
properties.put("nested", JsonObjectSchema.builder()
    .addStringProperty("subfield", "Nested field")
    .build());

// Set all properties at once
JsonSchema schema = JsonSchema.builder()
    .name("Example")
    .rootElement(JsonObjectSchema.builder()
        .properties(properties)
        .build())
    .build();
```

This workaround is functional but less intuitive than the builder pattern's usual fluent interface and requires maintaining a separate mutable map.

### PR DESCRIPTION
**Pull request by mariofusco**
Fix https://github.com/langchain4j/langchain4j/issues/2419

### CODE REVIEW

File: langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/json/JsonObjectSchema.java [hunk 1]
```diff
@@ -85,16 +85,16 @@ public Builder description(String description) {
          * @see #addEnumProperty(String, List)
          * @see #addEnumProperty(String, List, String)
          */
-        public Builder properties(Map<String, JsonSchemaElement> properties) {
```
Comment (dliubarskyi) [inline langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/json/JsonObjectSchema.java:88]: Can we make it in a non-breaking way? We can keep the old `properties()` method that is currently used by some users and mark it `@Deprecated`

**Review by dliubarskyi — COMMENTED** [review]
@mariofusco thank you!

File: langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/json/JsonObjectSchema.java (hunk 1 above)
Comment (mariofusco) [reply langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/json/JsonObjectSchema.java:88]: Done.

I was tempted to make it call the new `addProperties()` method, but since we are keeping this only for backward compatibility and will remove it soon I though to also leave it with the old behaviour.

**Review by dliubarskyi — APPROVED** [review]
@mariofusco thanks a lot!
