### PR TITLE
Include Metadata after Tika Parsing

### LINKED ISSUE #1974: [FEATURE]  ApacheTikaDocumentParser class does not include Metadata after parse
The ApacheTikaDocumentParser class does not include Metadata when returning a document after parsing it. 
Can you modify the code

```
public Document parse(InputStream inputStream) {
        try {
            Parser parser = parserSupplier.get();
            ContentHandler contentHandler = contentHandlerSupplier.get();
            Metadata metadata = metadataSupplier.get();
            ParseContext parseContext = parseContextSupplier.get();

            parser.parse(inputStream, contentHandler, metadata, parseContext);
            String text = contentHandler.toString();

            if (isNullOrBlank(text)) {
                throw new BlankDocumentException();
            }

            return Document.from(text);
        } catch (BlankDocumentException e) {
            throw e;
        } catch (ZeroByteFileException e) {
            throw new BlankDocumentException();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
return Document.from(text);
change to
return Document.from(text, metadata);

### PR DESCRIPTION
**Pull request by rzo1**
## Issue

Fixes #1974 

## Change

Add Metadata parsed by TIKA into the lc4j Metadata object for further usage.

Read the discussion about multi valued metadata entries but needed that fix in our use case anyway. Since parsed-by TIKA is the only actual multivalued metadata here, I decided to join it. 

## General checklist

- [x] There are no breaking changes
- [x] I have added unit and integration tests for my change
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

Note: Current main build is failing as well.

Site note: `ApacheTikaDocumentParserTest.should_parse_doc_ppt_and_pdf_files:33` fails on my OSX M3 system but seems to be fine on CI.

### CODE REVIEW

**Comment by langchain4j** [comment]
@rzo1 thank you! Could you please add the `includeMetadata` parameter (`false` by default) in the builder/ctor to make it configurable? Thanks!

**Comment by rzo1** [comment]
> @rzo1 thank you! Could you please add the `includeMetadata` parameter (`false` by default) in the builder/ctor to make it configurable? Thanks!

Yes. I just pushed the change.

File: document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java [hunk 1]
```diff
@@ -36,13 +38,15 @@ public class ApacheTikaDocumentParser implements DocumentParser {
     private final Supplier<Metadata> metadataSupplier;
     private final Supplier<ParseContext> parseContextSupplier;
 
+    private final boolean includeMetadata;
+
     /**
      * Creates an instance of an {@code ApacheTikaDocumentParser} with the default Tika components.
      * It uses {@link AutoDetectParser}, {@link BodyContentHandler} without write limit,
-     * empty {@link Metadata} and empty {@link ParseContext}.
+     * empty {@link Metadata} and empty {@link ParseContext}. By default, no metadata is included.
```
Comment (kpavlov) [inline document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java]: @rzo1 , is it a typo? Am I read correctly, that `false` means NOT included? Then the javadoc comment is not correct

File: document-parsers/langchain4j-document-parser-apache-tika/src/test/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParserTest.java [hunk 2]
```diff
@@ -34,14 +34,33 @@ void should_parse_doc_ppt_and_pdf_files(String fileName) {
...
+    })
+    void should_parse_doc_ppt_and_pdf_files_with_metadata(String fileName) {
+
+        DocumentParser parser = new ApacheTikaDocumentParser(AutoDetectParser::new, null, null, null, true);
+        InputStream inputStream = getClass().getClassLoader().getResourceAsStream(fileName);
+
+        Document document = parser.parse(inputStream);
+
+        assertThat(document.text()).isEqualToIgnoringWhitespace("test content");
+        assertThat(document.metadata().toMap()).isNotEmpty();
```
Comment (kpavlov) [inline document-parsers/langchain4j-document-parser-apache-tika/src/test/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParserTest.java]: Is it possible to assert something about the metadata, e.g. filename?

**Review by kpavlov — COMMENTED** [review]
Thank you, @rzo1 Is there a typo?

File: document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java (hunk 1 above)
Comment (rzo1) [reply document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java]: `false` is similar to "do not include metadata in the parsed" document. 

The Supplier for `Metadata` via the ctr argument is a way to customize the actual metadata for a parsed document.

I will change the sentence to: "Note: By default, no metadata is added to the parsed document.". Hopefully, this makes it clearer?

File: document-parsers/langchain4j-document-parser-apache-tika/src/test/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParserTest.java (hunk 2 above)
Comment (rzo1) [reply document-parsers/langchain4j-document-parser-apache-tika/src/test/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParserTest.java]: The filename is not part of the metadata provided by Tika. What is common in all files, is the Tika specific metadata for which class has parsed it. I added a check.

**Comment by kpavlov** [comment]
@rzo1 , would you mind to run `make format`?

**Comment by rzo1** [comment]
@kpavlov Done

**Comment by rzo1** [comment]
Anything missing?

File: document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java [hunk 3]
```diff
@@ -76,19 +79,21 @@ public ApacheTikaDocumentParser(Parser parser,
      * @param contentHandlerSupplier Supplier for Tika content handler. Default: {@link BodyContentHandler} without write limit
      * @param metadataSupplier       Supplier for Tika metadata. Default: empty {@link Metadata}
      * @param parseContextSupplier   Supplier for Tika parse context. Default: empty {@link ParseContext}
+     * @param includeMetadata        Whether to include metadata in the parsed document
      */
-    public ApacheTikaDocumentParser(Supplier<Parser> parserSupplier,
-                                    Supplier<ContentHandler> contentHandlerSupplier,
-                                    Supplier<Metadata> metadataSupplier,
-                                    Supplier<ParseContext> parseContextSupplier) {
+    public ApacheTikaDocumentParser(
```
Comment (langchain4j) [inline document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java:115]: This is a breaking change, please create a new ctor with 5 fields and deprecate this one

Comment (langchain4j) [reply document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java:115]: So the only way user can include metadata is to use this ctor that forces user to configure lots of suppliers? Perhaps we should have a more user friendly way to do so? Like `new ApacheTikaDocumentParser(true)` or `ApacheTikaDocumentParser.builder().includeMetadata(true).build()`, WDYT?

**Review by ghost — COMMENTED** [review]
@rzo1 thank you!

File: document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java (hunk 3 above)
Comment (rzo1) [reply document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java:115]: @langchain4j Here you go: https://github.com/langchain4j/langchain4j/pull/2192/commits/8c2fade93a98c9638a995cbd8c9b01038bf72925

**Comment by rzo1** [comment]
Anything left?

File: document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java (hunk 3 above)
Comment (mariofusco) [reply document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java:115]: > So the only way user can include metadata is to use this ctor that forces user to configure lots of suppliers? Perhaps we should have a more user friendly way to do so? Like `new ApacheTikaDocumentParser(true)` or `ApacheTikaDocumentParser.builder().includeMetadata(true).build()`, WDYT?

I agree on having at least a ctor overload like `new ApacheTikaDocumentParser(true)` to allow users to conveniently have metadata included.

**Comment by mariofusco** [comment]
> Anything left?

Imo just this https://github.com/langchain4j/langchain4j/pull/2192/files#r1922068486

File: document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java (hunk 3 above)
Comment (rzo1) [reply document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java:115]: The current diff has this constructor available: `new ApacheTikaDocumentParser(true)`

**Comment by rzo1** [comment]
> > Anything left?
> 
> Imo just this https://github.com/langchain4j/langchain4j/pull/2192/files#r1922068486

The overloaded ctor is available.

**Review by mariofusco — APPROVED** [review]

**Comment by dliubarskyi** [comment]
@rzo1 thank you!
