### PR TITLE
Bedrock anthropic sanitizer

### LINKED ISSUE #1864: [BUG] Bedrock invocation fails if the first message on messageList not use the user role
**Describe the bug**
Bedrock invocation fails if the first message on messageList is not use the user role

`Caused by: java.lang.RuntimeException: software.amazon.awssdk.services.bedrockruntime.model.ValidationException: messages: first message must use the "user" role (Service: BedrockRuntime, Status Code: 400, Request ID: 329e1228-505e-4c88-b72d-5672622010a2)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.bedrock.BedrockAnthropicMessageChatModel.generate(BedrockAnthropicMessageChatModel.java:144)
	at dev.langchain4j.model.bedrock.BedrockAnthropicMessageChatModel.generate(BedrockAnthropicMessageChatModel.java:105)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:238)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:110)
	at com.pagseguro.atendimento.lambda.bedrock.BedrockLangchainService$$QuarkusImpl.generativeChat(Unknown Source)
	at com.pagseguro.atendimento.lambda.bedrock.BedrockLangchainService$$QuarkusImpl_ClientProxy.generativeChat(Unknown Source)
	at com.pagseguro.atendimento.lambda.bedrock.BedrockService.generateChatFromAIService(BedrockService.java:49)
	at com.pagseguro.atendimento.lambda.bedrock.BedrockService_ClientProxy.generateChatFromAIService(Unknown Source)
	at com.pagseguro.atendimento.lambda.chatbot.ChatbotService.proccessChat(ChatbotService.java:182)
	... 6 more
Caused by: software.amazon.awssdk.services.bedrockruntime.model.ValidationException: messages: first message must use the "user" role (Service: BedrockRuntime, Status Code: 400, Request ID: 329e1228-505e-4c88-b72d-5672622010a2)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:38)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:55)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:224)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
	at software.amazon.awssdk.services.bedrockruntime.DefaultBedrockRuntimeClient.invokeModel(DefaultBedrockRuntimeClient.java:149)
	at dev.langchain4j.model.bedrock.internal.AbstractBedrockChatModel.invoke(AbstractBedrockChatModel.java:127)
	at dev.langchain4j.model.bedrock.BedrockAnthropicMessageChatModel.lambda$generate$0(BedrockAnthropicMessageChatModel.java:144)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	... 16 more`

**To Reproduce**
This error can be easily reproduced, the default model chatMemory message window is 10 messages, when the 11th message comes, the first is deleted, if the newer remaining message is not a user role message then the error happen

**Expected behavior**
You should not need to worry with what is the first message in the chatMemory

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: anthropic.claude-3-5-sonnet-20240620-v1:0
- Java version: 21
- Quarkus version: 3.12.3

### PR DESCRIPTION
**Pull request by rndtavares**
## Issue
Closes #1864

## Change
Moving anthropic message sanitizer from anthropic to core, and using it on bedrock anthropic message chat model and streaming chat model

## General checklist

- [X] There are no breaking changes
- [x] I have added unit and integration tests for my change
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by rndtavares** [comment]
Tests ok in bedrock module and core module (where message sanitizer was moved)

image


image

**Review by ghost — COMMENTED** [review]
@rndtavares thanks!

I am not sure about this solution, it requires putting Anthropic-specific logic into the core. I suppose this is done to reduce the duplication, but it brings it's own issues. What about duplicating this code in bedrock module? Another option would be to create a common anthropic-core module and have this logic there, but this seems to be overcomplicating things. I guess it is OK to live with a bit of duplication. Just make sure to "link" both parts (e.g. with a Javadoc comment) so that when one is updated, person will know that there is another place like this.

**Comment by rndtavares** [comment]
> @rndtavares thanks!
> 
> I am not sure about this solution, it requires putting Anthropic-specific logic into the core. I suppose this is done to reduce the duplication, but it brings it's own issues. What about duplicating this code in bedrock module? Another option would be to create a common anthropic-core module and have this logic there, but this seems to be overcomplicating things. I guess it is OK to live with a bit of duplication. Just make sure to "link" both parts (e.g. with a Javadoc comment) so that when one is updated, person will know that there is another place like this.

done

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java [hunk 1]
```diff
@@ -63,4 +69,10 @@ public enum Types {
             this.value = modelID;
         }
     }
+
+    @Override
+    public Response<AiMessage> generate(List<ChatMessage> messages) {
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: What about other `generate` methods?

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java [hunk 2]
```diff
@@ -30,4 +37,10 @@ public enum Types {
             this.value = modelID;
         }
     }
+
+    @Override
+    public void generate(List<ChatMessage> messages, StreamingResponseHandler<AiMessage> handler) {
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java]: same here

**Review by ghost — COMMENTED** [review]
@rndtavares thank you!

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java (hunk 1 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: done for all methods

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java (hunk 2 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java]: done for all generate methods

image

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java [hunk 3]
```diff
@@ -63,4 +73,36 @@ public enum Types {
             this.value = modelID;
         }
     }
+
+    @Override
+    public String generate(final String userMessage) {
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: Overriding `generate(String)` does not seem necessary.

Only these should be overriden and explicitly sanitize messages:
`generate(List<ChatMessage> messages)`
`generate(List<ChatMessage> messages, List<ToolSpecification> toolSpecifications)`
`generate(List<ChatMessage> messages, ToolSpecification toolSpecification)`

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java [hunk 4]
```diff
@@ -63,4 +73,36 @@ public enum Types {
...
+        if (Objects.isNull(userMessage) || userMessage.isEmpty()) {
+            throw illegalArgument("%s cannot be null or empty", "message");
+        }
+        return super.generate(userMessage);
+    }
+
+    @Override
+    public Response<AiMessage> generate(final ChatMessage... messages) {
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: this is not needed either

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java:1]: Should this be fixed for `BedrockAnthropicCompletionChatModel` though? 
I thought that this a problem only for `BedrockAnthropicMessageChatModel`?

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java [hunk 5]
```diff
@@ -63,4 +73,36 @@ public enum Types {
...
+    @Override
+    public Response<AiMessage> generate(List<ChatMessage> messages) {
+        List<ChatMessage> sanitizedMessages = sanitizeMessages(messages);
+        return super.generate(sanitizedMessages);
+    }
+
+    @Override
+    public Response<AiMessage> generate(final List<ChatMessage> messages, final List<ToolSpecification> toolSpecifications) {
+        List<ChatMessage> sanitizedMessages = sanitizeMessages(messages);
+        return super.generate(sanitizedMessages, toolSpecifications);
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: this will throw an exception... what's the point?

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java [hunk 6]
```diff
@@ -63,4 +73,36 @@ public enum Types {
...
+    }
+
+    @Override
+    public Response<AiMessage> generate(final List<ChatMessage> messages, final ToolSpecification toolSpecification) {
+        List<ChatMessage> sanitizedMessages = sanitizeMessages(messages);
+        return super.generate(sanitizedMessages, toolSpecification);
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: same here

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java (hunk 1 above)
Comment (langchain4j) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: I guess this comment made sense only for `BedrockAnthropicMessageChatModel`, sorry for confusion

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java [hunk 7]
```diff
@@ -92,6 +95,20 @@ protected Map<String, Object> getRequestParameters(String prompt) {
         return parameters;
     }
 
+    @Override
+    public String generate(final String userMessage) {
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java]: not needed

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java [hunk 8]
```diff
@@ -92,6 +95,20 @@ protected Map<String, Object> getRequestParameters(String prompt) {
...
+        if (Objects.isNull(userMessage) || userMessage.isEmpty()) {
+            throw illegalArgument("%s cannot be null or empty", "message");
+        }
+        return super.generate(userMessage);
+    }
+
+    @Override
+    public Response<AiMessage> generate(final ChatMessage... messages) {
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java]: not needed

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java (hunk 1 above)
Comment (langchain4j) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: OK, it does not make sense for `BedrockAnthropicMessageChatModel` either 😅 Sorry

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java [hunk 9]
```diff
@@ -30,4 +41,36 @@ public enum Types {
...
+    @Override
+    public void generate(final UserMessage userMessage, final StreamingResponseHandler<AiMessage> handler) {
+        List<ChatMessage> sanitizedMessages = sanitizeMessages(List.of(userMessage));
+        super.generate(sanitizedMessages, handler);
+    }
+
+    @Override
+    public void generate(final List<ChatMessage> messages, final List<ToolSpecification> toolSpecifications, final StreamingResponseHandler<AiMessage> handler) {
+        List<ChatMessage> sanitizedMessages = sanitizeMessages(messages);
+        super.generate(sanitizedMessages, toolSpecifications, handler);
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java]: this will throw an exception anyway, please remove this overriden method

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java [hunk 10]
```diff
@@ -30,4 +41,36 @@ public enum Types {
...
+    }
+
+    @Override
+    public void generate(final List<ChatMessage> messages, final ToolSpecification toolSpecification, final StreamingResponseHandler<AiMessage> handler) {
+        List<ChatMessage> sanitizedMessages = sanitizeMessages(messages);
+        super.generate(sanitizedMessages, toolSpecification, handler);
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java]: same here (exception)

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java [hunk 11]
```diff
@@ -30,4 +41,36 @@ public enum Types {
             this.value = modelID;
         }
     }
+
+    @Override
+    public void generate(final UserMessage userMessage, final StreamingResponseHandler<AiMessage> handler) {
+        List<ChatMessage> sanitizedMessages = sanitizeMessages(List.of(userMessage));
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java]: does it make sense to sanitize single user message?

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java [hunk 12]
```diff
@@ -30,4 +41,36 @@ public enum Types {
...
+    }
+
+    @Override
+    public void generate(final List<ChatMessage> messages, final ToolSpecification toolSpecification, final StreamingResponseHandler<AiMessage> handler) {
+        List<ChatMessage> sanitizedMessages = sanitizeMessages(messages);
+        super.generate(sanitizedMessages, toolSpecification, handler);
+    }
+
+    @Override
+    public void generate(final String userMessage, final StreamingResponseHandler<AiMessage> handler) {
```
Comment (langchain4j) [inline langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java]: why is this required?

**Comment by langchain4j** [comment]
@rndtavares thank you!

Please check failing build, formatting is off

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java (hunk 3 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: fixed, sorry for that

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java (hunk 4 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: removed

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java:1]: now I've made some tests with completion model and saw that it does not need sanitization, models supported by `BedrockAnthropicCompletionChatModel` does not use a messageList that needs sanitization, it send the text in the prompt field like that:

image

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java (hunk 5 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: removed

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java (hunk 6 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicCompletionChatModel.java]: removed

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java (hunk 7 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java]: removed

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java (hunk 8 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java]: removed

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java (hunk 9 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java]: removed

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java (hunk 10 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java]: removed

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java (hunk 11 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java]: removed

File: langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java (hunk 12 above)
Comment (rndtavares) [reply langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java]: I've made some tests with streaming models too, and now I saw that it is not necessary

image

**Comment by rndtavares** [comment]
> @rndtavares thank you!
> 
> Please check failing build, formatting is off

fixed

**Review by ghost — APPROVED** [review]
@rndtavares thanks a lot!
