### PR TITLE
Fix for #2613, MCP Tool execution error handling is not correct

### LINKED ISSUE #2613: [BUG] MCP Tool execution error handling is  not correct
Tool execution errors are not properly returned.

In the class ToolExecutionHelper, there is 2 issues:
* If the reply contains an `error` element, the message and code are swallowed and not returned.
* If the reply contains a `content` element, there is no check done for `isError`. This should be exposed in the reply.

**Describe the bug**
Tool execution errors are not properly returned.

**Log and Stack trace**

**To Reproduce**
Call a tool that reply with the 2 kind of errors.

**Expected behavior**

* If there is an `error` element to have the following returned value: `There was an error executing the tool. Message: actual message, code: actual code`

* If there is an `isError` field to have the following reurned value: `There was an error executing the tool. content text`

**Please complete the following information:**
- LangChain4j version: 1.0.0.beta1
- LLM(s) used:  Any
- Java version: JDK21
- Spring Boot version (if applicable): 

**Additional context**

### PR DESCRIPTION
**Pull request by jfdenise**
## Issue

Fixes #2613

## Change
Handle the error cases. Add new integration test. Update existing ones.

NOTE: I have failing tests in the langchain4j module caused by missing API KEY, I am pretty sure those failures are not caused by my chages.

## General checklist

- [X] There are no breaking changes
- [X] I have added unit and/or integration tests for my change
- [ ] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [X] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by dliubarskyi** [comment]
cc @jmartisk

File: langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/ToolExecutionHelper.java [hunk 1]
```diff
@@ -20,7 +20,15 @@ static String extractResult(JsonNode result) {
...
             JsonNode resultNode = result.get("result");
             if (resultNode.has("content")) {
-                return extractSuccessfulResult((ArrayNode) resultNode.get("content"));
+                String content = extractSuccessfulResult((ArrayNode) resultNode.get("content"));
+                boolean isError = false;
+                if (resultNode.has("isError")) {
+                    isError = resultNode.get("isError").asBoolean();
+                }
+                if (isError) {
+                    content = String.format(EXECUTION_ERROR_MESSAGE + ". %s", content);
```
Comment (jmartisk) [inline langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/ToolExecutionHelper.java]: I think it would be clearer if we used `:` instead of `.` between these two strings. Or maybe, even better, something like `EXECUTION_ERROR_MESSAGE + ". The tool returned: %s"` 

Maybe we should make this whole thing customizable (add an SPI for applications to plug in a Supplier of error messages) but that will be a separate enhancement I guess

Comment (jfdenise) [reply langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/ToolExecutionHelper.java]: @jmartisk , thank-you. I updated as you suggested.

**Review by jmartisk — APPROVED** [review]
Nice!
