### PR TITLE
Revisit AiServices.tools() validation

### LINKED ISSUE #4028: Revisit AiServices.tools() validation
Sometimes (also because of the overloaded `tools()` method) tools can be specified incorrectly. For example: https://github.com/langchain4j/langchain4j/issues/4023#issuecomment-3517865529

Consider adding a strict validation that verifies that each object has at least one `@Tool`-annotated method.
Or at least check for the common cases of misuse (e.g. nested Collection/Iterable in a List).

### PR DESCRIPTION
**Pull request by oscerd**
## Issue

Closes #4028

## Change

Changing the validation logic.

## General checklist

- [ ] There are no breaking changes (API, behaviour) 
- [x] I have added unit and/or integration tests for my change
- [x] The tests cover both positive and negative cases
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by oscerd** [comment]
Error doesn't seem to be related

File: langchain4j/src/main/java/dev/langchain4j/service/tool/ToolService.java [hunk 1]
```diff
@@ -97,9 +97,25 @@ public void tools(Collection<Object> objectsWithTools) {
...
+                        objectWithTool.getClass().getName());
+            }
+
+            boolean hasToolMethod = false;
             for (Method method : objectWithTool.getClass().getDeclaredMethods()) {
-                getAnnotatedMethod(method, Tool.class)
-                        .ifPresent(toolMethod -> processToolMethod(objectWithTool, toolMethod));
+                if (getAnnotatedMethod(method, Tool.class).isPresent()) {
+                    hasToolMethod = true;
+                    processToolMethod(objectWithTool, method);
```
Comment (dliubarskyi) [inline langchain4j/src/main/java/dev/langchain4j/service/tool/ToolService.java:111]:
```suggestion
                    processToolMethod(objectWithTool, toolMethod);
```

There are currently 2 tests failing because of this: `AiServicesWithToolsIT.tools_as_agents_tests`

Comment (oscerd) [reply langchain4j/src/main/java/dev/langchain4j/service/tool/ToolService.java:111]: I'll check this. Thanks. Locally it was passing.

Comment (dliubarskyi) [reply langchain4j/src/main/java/dev/langchain4j/service/tool/ToolService.java:111]: I will fix it after the merge

**Review by dliubarskyi — APPROVED** [review]
@oscerd thank you!

**Comment by oscerd** [comment]
Thanks,I hope to contribute more next year!
