### PR TITLE
Missing interrupt status handling in RetryUtils (issue #4479)

### LINKED ISSUE #4479: [BUG] Missing interrupt status handling in RetryUtils
**Describe the bug**
RetryUtils fails to propagate the InterruptedException, causing the loop to continue retrying.

**Log and Stack trace**
N/A

**To Reproduce**
```
        ExecutorService executor = Executors.newSingleThreadExecutor();
        Future<?> future = executor.submit(() -> {
            model.chat("how are you"); // any model that uses RetryUtils
        });

        try {
            future.get(2, TimeUnit.SECONDS); // time out exceeds
        } catch (TimeoutException e) {
            future.cancel(true); // try to interrupt thread
        } catch (ExecutionException | InterruptedException e) {
            throw new RuntimeException(e);
        } finally {
            executor.shutdownNow();
        }
```

**Expected behavior**
I expect the thread to be interrupted and no new retries to be made after calling future.cancel(true).

**Expected fix:**
adding this inside while loop
```
  if (Thread.currentThread().isInterrupted()) {
            throw new RuntimeException("Execution cancelled by user");
        }
```

**Please complete the following information:**
- LangChain4j version: Latest main branch
- LLM(s) used: N/A
- Java version:  21
- Spring Boot version (if applicable): N/A

**Additional context**
You can see now spring Retryable  handles such behaviour, it stops retries and throws BackOffInterruptedException

### PR DESCRIPTION
**Pull request by isergeymd**
## Issue

Closes #4479

## Change
I've added check if thread isInterrupted and rethrowing exception

## General checklist

- [x] There are no breaking changes (API, behaviour)
- [x] I have added unit and/or integration tests for my change
- [x] The tests cover both positive and negative cases
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

File: langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java [hunk 1]
```diff
@@ -164,12 +164,12 @@ public int jitterDelayMillis(int retry) {
...
          */
-        @JacocoIgnoreCoverageGenerated
         public void sleep(int retry) {
             try {
                 Thread.sleep(jitterDelayMillis(retry));
-            } catch (InterruptedException ignored) {
-                // pass
+            } catch (InterruptedException e) {
+                Thread.currentThread().interrupt();
+                throw new RuntimeException("Interrupted during sleep", e);
```
Comment (dliubarskyi) [inline langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java]:
```suggestion
                throw new RuntimeException("Interrupted while retrying", e);
```

File: langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java [hunk 2]
```diff
@@ -205,6 +205,10 @@ public <T> T withRetry(Callable<T> action, int maxRetries) {
                 } catch (NonRetriableException e) {
                     throw e;
                 } catch (Exception e) {
+                    if (Thread.currentThread().isInterrupted()) {
+                        throw new RuntimeException("Interrupted during action execution", e);
```
Comment (dliubarskyi) [inline langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java:209]: Please explain why is this change needed?
It is also not testep, please add a test if required

Comment (isergeymd) [reply langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java:209]: In this line, we break from the while loop to stop retrying (the main point of this PR). We handle the Exception here and check .isInterrupted() because it is the only way to do it; for example, JdkHttpClient wraps InterruptedException in a RuntimeException

should_not_retry_after_interruption - here is the test

Comment (dliubarskyi) [reply langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java:209]: If you remove this part and run `should_not_retry_after_interruption`, it will pass. So either there is something wrong with the implementation, or with test, please check.

I guess we can indeed remove this part and rely only on the check inside the `sleep` method. If `sleep` method throws an exception, you break out of `while` loop.

File: langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java [hunk 3]
```diff
@@ -164,12 +164,12 @@ public int jitterDelayMillis(int retry) {
...
          */
-        @JacocoIgnoreCoverageGenerated
         public void sleep(int retry) {
             try {
                 Thread.sleep(jitterDelayMillis(retry));
-            } catch (InterruptedException ignored) {
-                // pass
+            } catch (InterruptedException e) {
+                Thread.currentThread().interrupt();
+                throw new RuntimeException("Interrupted while sleep", e);
```
Comment (dliubarskyi) [inline langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java]:
```suggestion
                throw new RuntimeException("Interrupted while retrying", e);
```
I am not sure "sleep" is the most important part here

File: langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java (hunk 2 above)
Comment (isergeymd) [reply langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java:209]: I think it needs to be tested differently... Theoretically, it is possible to interrupt the thread in both cases: while sleeping and during action.call() (for example, in a JdkHttpClient sync call).

Comment (isergeymd) [reply langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java:209]: i've added send test to cover both cases.

Here why we should not remove this part with .isInterrupted()
1) Prevents misleading "retriable error" logs
2) Checking the interrupt flag is a lightweight memory check. It is significantly more efficient than relying on Thread.sleep() to trigger a costly native exception

**Review by dliubarskyi — APPROVED** [review]
@isergeymd thank you!
