### PR TITLE
fix: include enum values in List, Set, and array format instructions (#4464)

### LINKED ISSUE #4464: [BUG] AIService Output List<Enum> missing Enum schema description
**Describe the bug**

private static String typeOf(Field field, Set<Class<?>> visited) {
        Type type = field.getGenericType();

        if (type instanceof ParameterizedType parameterizedType) {
            Type[] typeArguments = parameterizedType.getActualTypeArguments();

            if (parameterizedType.getRawType().equals(List.class)
                    || parameterizedType.getRawType().equals(Set.class)) {
                return format("array of %s", 
                     <font color="red">
                             simpleNameOrJsonStructure((Class<?>) typeArguments[0], visited)
                     </font>
                  );
            }
        } else if (field.getType().isArray()) {
            return format("array of %s", simpleNameOrJsonStructure(field.getType().getComponentType(), visited));
        } else if (((Class<?>) type).isEnum()) {
            return "enum, must be one of " + Arrays.stream(((Class<?>) type).getEnumConstants())
                    .map(e -> ((Enum<?>) e).name())
                    .toList();
        }

        return simpleNameOrJsonStructure(field.getType(), visited);
    }

**Expected behavior**
private static String typeOf(Field field, Set<Class<?>> visited) {
        Type type = field.getGenericType();

        if (type instanceof ParameterizedType parameterizedType) {
            Type[] typeArguments = parameterizedType.getActualTypeArguments();

            if (parameterizedType.getRawType().equals(List.class)
                    || parameterizedType.getRawType().equals(Set.class)) {
                return format("array of %s", 
                            <font color="red">
                                    typeof((Class<?>) typeArguments[0], visited)
                            </font>
                     );
            }
        } else if (field.getType().isArray()) {
            return format("array of %s", simpleNameOrJsonStructure(field.getType().getComponentType(), visited));
        } else if (((Class<?>) type).isEnum()) {
            return "enum, must be one of " + Arrays.stream(((Class<?>) type).getEnumConstants())
                    .map(e -> ((Enum<?>) e).name())
                    .toList();
        }

        return simpleNameOrJsonStructure(field.getType(), visited);
    }

**Please complete the following information:**
- LangChain4j version: 1.10.0
- LLM(s) used: 
- Java version: 
- Spring Boot version (if applicable):

### PR DESCRIPTION
**Pull request by abhishek9773**
Closes #4464 

when an Enum is used inside a `List`,` Set`, or as an `Array`, the output parser fails to extract the `enum` constants, resulting in an empty JSON `object {}` in the format instructions.

image (6)

- I fixed this by refactoring `typeOf` into a recursive method that can drill down into `ParameterizedType` and `Array` types to find the underlying `Enum`.

## Change
- Made `typeOf` recursive to handle nested types.
- Added a regression test in `PojoOutputParserTest` to verify the fix.
- Ran `./mvnw spotless:apply -pl langchain4j` to ensure code style compliance.
## final Test 
`> ./mvnw test -pl langchain4j -Dtest=PojoOutputParserTest`

Screenshot from 2026-01-24 00-58-04

## General checklist

- [x] There are no breaking changes (API, behaviour)
- [x] I have added unit and/or integration tests for my change
- [x] The tests cover both positive and negative cases
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

File: langchain4j/src/main/java/dev/langchain4j/service/output/PojoOutputParser.java [hunk 1]
```diff
@@ -94,12 +94,11 @@ private static String typeOf(Field field, Set<Class<?>> visited) {
 
     private static String typeOf(Type type, Set<Class<?>> visited) {
         if (type instanceof ParameterizedType parameterizedType) {
-            Type[] typeArguments = parameterizedType.getActualTypeArguments();
             Type rawType = parameterizedType.getRawType();
 
-            if (rawType.equals(List.class) || rawType.equals(Set.class)) {
+            if (rawType instanceof Class<?> rawClass && (rawClass == List.class || rawClass == Set.class)) {
```
Comment (abhishek9773) [inline langchain4j/src/main/java/dev/langchain4j/service/output/PojoOutputParser.java:99]: Switched to `instanceof` pattern matching to ensure `rawType` is a Class before performing identity (==) checks, making List/Set detection safer and more robust

**Review by dliubarskyi — APPROVED** [review]
@abhishek9773 thank you!
